<img src="./assets/numpy_logo.png" alt="logo" width="400"/>

## Introduction to numpy

NumPy stands for 'Numerical Python'. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrices, along with many high-level mathematical functions that operate on these arrays and matrices. It contains among other things:

→ a powerful N-dimensional array object

→ sophisticated (broadcasting) functions

→ tools for integrating C/C++ and Fortran code

→ useful linear algebra, Fourier transform, and random number capabilities

## Installing NumPy
When you want to work with numpy locally, you should run the following commands:

You can install NumPy with:\
`pip install numpy`\
or\
`conda install numpy`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.

## Why should we use NumPy?

Numpy is a library to perform numerical calculation in python. We will use it mainly because it allows us to create and modify matrices, and to do operations on them with ease.

NumPy is, like Pandas, Matplotlib or Scikit-Learn, one of the packages that you cannot miss when you are learning Machine Learning, mainly because this library provides a matrix data structure that has some benefits over regular Python lists. Some of these benefits are: being more compact, quicker access to reading and writing articles, being more convenient and more efficient.

For example, we will see later in the bootcamp that working with images means dealing with three-dimensional matrices as large as 3840 x 2160, which means we will have 3×3840×2160 = 24883200 entries!!! 😱😱😱.

Working with matrices of that magnitude is practically impossible to carry out with lists and dictionaries if one wants to have an efficient and fast programming.

#### Exercise: Import the numpy package under the name `np` (★☆☆)

`numpy` is commonly imported as `np` so we highly recommend to put this alias.

In [2]:
import numpy as np

## What is an array and why it is importante for machine learning?

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.


![alt text](assets/1D.png "1D")

We can have arrays from several dimension. Neural networks sometimes deal with 4D arrays. An array is known as the central data structure of the NumPy library. Array in NumPy is called as NumPy Array. Later, we will use also other kind of arrays thar are called: Tensors.

![alt text](./assets/3D.png "3D")

#### Exercise: Print the numpy version and the configuration (★☆☆)

You can print the version of any package of Python using `name_of_package.__version__`

In [3]:
import numpy as np
print(np.__version__)

1.22.1


#### Exercise: Create a null vector of size 10 (★☆☆)

A `null vector` is an array of zeros (`0`), also called `inicializacion vector`.

Check de function `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise: Create a vector of ones with size 10 (★☆☆)
Check de function `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise: Create an 1D array with specific start value, end value and number of values (★☆☆)

Check the function `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [6]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Run: Create a vector (1D array) with random integers from 10 to 49 and dimension 1x35 (★☆☆)

When `dimension` is expressed `1x35` it means: One dimension array with 35 items (length=35).

Check the function `np.random` which allows you to create random arrays (https://numpy.org/doc/1.16/reference/routines.random.html)

In [7]:
import numpy as np

## 10 random numbers between (0, 1)
print(np.random.random(10))
## 35 random numbers between (10, 49)
print(np.random.random(35)*39 + 10)  

[0.01260663 0.8818753  0.54460935 0.36040791 0.22155227 0.16470488
 0.79944746 0.52420995 0.90466667 0.32651527]
[48.01926604 33.4356761  29.65164265 10.39230135 32.84338559 23.74406723
 15.30167679 30.96844184 16.31147866 33.2301292  21.0544143  45.81059511
 29.09608358 15.2200887  38.63263656 37.26786746 32.49983036 43.969943
 24.55376825 18.98082325 46.6675779  21.7755511  31.81748449 14.35209957
 30.94629097 24.00491969 33.78241439 15.72209668 16.20820129 18.02605959
 23.80279239 47.79093385 24.25665455 35.27611233 37.92977103]


In [8]:
## Two ways to create numbers with normal distribution
print(np.random.rand(10)) # 10 random values with distribution N(0,1)
print(np.random.normal(loc = 0, scale = 1, size = 10)) # 10 random values with distribution N(0,1)

[0.9539093  0.13245712 0.81172048 0.64489847 0.62050556 0.10022147
 0.13871224 0.85738462 0.27342889 0.33783226]
[ 0.31257028  1.08298692 -0.33419356  0.48273322  1.06281099 -0.58392607
  0.64873179  0.93363674 -0.05030671  0.32330307]


In [9]:
## Did you notice the difference between both functions? 
print(np.random.normal(loc = -5, scale = 33, size = 10)) # 10 random values with distribution N(-5,33)

[  -5.87593    -100.31312861  -57.38032857    5.28320256   30.09554604
  -58.66449185   84.30729175   38.50535286    5.05691752  -24.02224524]


In [10]:
## 10 random values with uniform distribution. That is, all values have the same probability
print(np.random.uniform(-30,100,10)) # All values are between -30 and 100.

[ 64.18706413  78.52079509  38.58723062  82.4805702   -3.22672145
  88.84583746 -24.48723906 -12.21302256  93.50811893 -17.87048755]


In [11]:
# 10 integers values between 0 and 100.
print(np.random.randint(0, 100, 10))

[11 83 26 70 52 21 52 92 32  4]


In [12]:
# 10 random values with Chi distribution with 5 degrees of freedom
print(np.random.chisquare(5,10))

[13.69591957  8.45513885  5.19562671  4.73191917  7.82104046  4.04724307
 15.75085454  3.15281012  6.6997988   5.40367383]


The above examples are the most common distribution and random values you will learn throughout the bootcamp. Now, let's deal with those arrays.

#### Exercise: Reverse one of the last vector we created before (first element becomes last) (★☆☆)
Try with `[::-1]`

In [13]:
rand_int_vect = np.random.randint(0, 100, 10)
print(rand_int_vect)
print(rand_int_vect[::-1])

[76 86 85 90 44 67  8  2 37 33]
[33 37  2  8 67 44 90 85 86 76]


#### Exercise: Create a 5x5 identidy matrix (★☆☆)
Check the function `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [14]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Exercise: Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
Check the function `where`(https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [15]:
print(np.where(np.array([1,2,0,0,4,0]) != 0)[0])

[0 1 4]


#### Exercise: Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Check the function `min`(https://numpy.org/devdocs/reference/generated/numpy.where.html) and `max`(https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [16]:
arr_10_by_10 = np.random.random((10,10))
print(arr_10_by_10.min())
print(arr_10_by_10.max())

0.009603058760232486
0.9928853102213592


#### Exercise: Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
print(np.random.random(30).mean())

0.5153485611073


#### Exercise: Define a function with input your date of birth (yyyy/mm/dd) that returns a random array with the following dimensions: (★★☆)
$$yyyy-1900 \times |mm - dd|$$

In [18]:
def birth_date(date_of_birth: str) -> np.array:
    date = date_of_birth.split("/")
    size = (int(date[0]) - 1900, np.abs(int(date[1]) - int(date[2])))
    return np.random.random(size) 

birthdate = input("enter your birthday: ")
print(birth_date(birthdate).shape)

(99, 16)


## What is the difference between Python List and a Numpy Array?

- Python list can contain elements with different data types whereas Numpy Array‘s elements are always homogeneous (same data types).
- NumPy arrays are faster and more compact than Python lists.

## Why NumPy Arrays are faster than Lists?

- NumPy Array uses fixed memory to store data and less memory than Python lists.
- Contiguous memory allocation in NumPy Arrays.

#### Exercise: Convert the list `my_list = [1, 2, 3]` to numpy array (★☆☆)

In [19]:
my_list = [1, 2, 3]
numpy_my_list = np.array(my_list)
print(my_list)
print(numpy_my_list)

[1, 2, 3]
[1 2 3]


#### Exercise: Convert the tuple `my_list = (1, 2, 3)` to numpy array (★☆☆)

In [20]:
my_list = (1, 2, 3)
numpy_my_list = np.array(my_list)
print(my_list)
print(numpy_my_list)

(1, 2, 3)
[1 2 3]


#### Exercise: Convert the list of tuples `my_list = [(1,2,3), (4,5)]` to numpy array (★☆☆)

In [21]:
my_list = [(1, 2, 3), (4,5)]
numpy_my_list = np.array(my_list, dtype=np.ndarray)
print(my_list)
print(numpy_my_list)

[(1, 2, 3), (4, 5)]
[(1, 2, 3) (4, 5)]


#### Exercise: Resize a random array of dimensions 5x12 into 12x5 (★☆☆)
Check `reshape`from `numpy`(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [22]:
size1 = 5,12
size2 = 12,5
arr1 = np.random.random(size1)
arr2 = arr1.reshape(size2)
print(arr1.shape)
print(arr2.shape)

(5, 12)
(12, 5)


#### Exercise: Create a function that normalize a 5x5 random matrix (★☆☆)
Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :
$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$


In [23]:
arr_to_normalize = np.random.random((5,5))
arr_normalized = (arr_to_normalize - arr_to_normalize.mean()) / arr_to_normalize.std()
print(arr_normalized)

[[-0.37183989  1.55443398  0.91242965 -0.14612413 -1.23656437]
 [-0.45206206  0.32059158  1.70240373  1.37201471 -0.78339161]
 [-0.80741467  0.42418178 -0.20367437 -1.3486471   0.53466445]
 [-1.50684102 -0.22124417 -0.65717982  1.30668431 -1.48865768]
 [-1.40424171 -0.31088386  0.90938652  0.90743219  0.99454356]]


## Stacking numpy arrays

Stacking is used to join a sequence of same dimension arrays along a new axis.
`numpy.stack(arrays,axis)` : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

### You have two ways to do it:


![alt text](./assets/stack.jpeg "stack")


### or


![alt text](./assets/stack2.jpeg "stack")




#### Exercise: Generate two random arrays with integers and apply the stacking using `stack` (★★☆)

In [24]:
arr_1 = np.random.randint(0, 10, (2,2))
arr_2 = np.random.randint(0, 10, (2,2))
print(arr_1)
print()
print(arr_2)
print()
print(np.stack((arr_1, arr_2)))

[[7 4]
 [1 5]]

[[4 3]
 [6 5]]

[[[7 4]
  [1 5]]

 [[4 3]
  [6 5]]]


#### Exercise: Generate two random arrays with integers and apply the stacking using `hstack` and `vstack` (★★☆)

In [25]:
arr_1 = np.random.randint(0, 10, (2,2))
arr_2 = np.random.randint(0, 10, (2,2))
print(arr_1)
print()
print(arr_2)
print()
print(np.hstack((arr_1, arr_2)))
print()
print(np.vstack((arr_1, arr_2)))

[[0 1]
 [5 4]]

[[3 8]
 [8 5]]

[[0 1 3 8]
 [5 4 8 5]]

[[0 1]
 [5 4]
 [3 8]
 [8 5]]


## Basic maths in numpy

You can make typical math operations like:

- Addition,Subtraction,Multiplication and Division between two arrays using numpy.
- Operation on array using sum() & cumsum() function.
- Minimum and Maximum value from an array
- Exponent/Power , Square Root and Cube Root functions

or even apply common trigonometric functions:

- `numpy.sin()`:  Sine (x) Function
- `numpy.cos()`: Cosine(x) Function
- `numpy.tan()`: Tangent(x)Function
- `numpy.sinh()`: Hyperbolic Sine (x) Function
- `numpy.cosh()`: Hyperbolic Cosine(x) Functionv
- `numpy.tanh()`: Hyperbolic Tangent(x)Function
- `numpy.arcsin()`: Inverse Sine Function
- `numpy.arccos()`: Inverse Cosine Function
- `numpy.arctan()`: Inverse Tangent Function
- `numpy.pi`: pi value
- `numpy.hypot(w,h)`: For calculating Hypotenuse $c = \sqrt{(w^2 + h^2)}$
- `numpy.rad2deg()`: Radians to degrees
- `numpy.deg2rad()`: Degrees to radians

#### Exercise: Generate two random 8 - dimensional vectors and apply the most common operation between vectors:  addition, substraction, multiplication, division(★☆☆)

Check the math functions here: https://numpy.org/doc/stable/reference/routines.math.html

In [26]:
vect_1 = np.random.random(8)
vect_2 = np.random.random(8)

print(vect_1 + vect_2)
print(vect_1 - vect_2)
print(vect_1 * vect_2)
print(vect_1 / vect_2)

[0.3421428  1.36355344 0.45581732 1.01541247 0.97570322 1.89492521
 1.07531862 1.32085966]
[ 0.07201947  0.32907867  0.07743666 -0.03510771 -0.35924083 -0.06686325
 -0.87222155  0.49079041]
[0.02796872 0.4377463  0.05044325 0.25745748 0.2057357  0.89656772
 0.09888492 0.37594875]
[1.53323397 1.63622367 1.40930558 0.93316128 0.46178894 0.9318344
 0.10428389 2.18252884]


#### Exercise: Generate two random matrices with dimensions between 5 and 10, e.g. 5x7 vs 8x9 and try. Were you able to do the matrix multiplication? why? (★★☆) 

In [27]:
matrix_1 = np.random.random((np.random.randint(5,10), np.random.randint(5,10)))
matrix_2 = np.random.random((np.random.randint(5,10), np.random.randint(5,10)))

print(matrix_1 + matrix_2)
print(matrix_1 - matrix_2)
print(matrix_1 / matrix_2)
print(matrix_1 * matrix_2)

ValueError: operands could not be broadcast together with shapes (9,9) (5,7) 

#### Exercise: Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array) Were you able to do the matrix multiplication? (★★☆) 

$$ a = \left(\begin{matrix}
0 & 1 & 2\\ 
3 & 4 & 5\\ 
6 & 7 & 8
\end{matrix}\right)$$

$$ b = \left(\begin{matrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{matrix}\right)$$




In [28]:
a = np.linspace(0, 8, 9).reshape((3,3))
b = np.linspace(2, 10, 9).reshape((3,3))
print(a)
print(b)
print(a * b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 0.  3.  8.]
 [15. 24. 35.]
 [48. 63. 80.]]


#### Exercise: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★★☆)

In [29]:
matrix_1 = np.random.random((5, 3))
matrix_2 = np.random.random((3, 2))

print(np.dot(matrix_1, matrix_2))

[[0.23916821 0.15273904]
 [0.45956707 0.22654334]
 [0.63009061 0.49436448]
 [0.10113814 0.21254501]
 [0.21808672 0.16110318]]


## Data types

Do you think the following preposition is true?
`8==8`

Surely you will definetely say yes, which is true mathematically, but computationally it is not always the same, at least in terms of memory. For example, run the following cell:

In [30]:
import sys

# int64
x = np.array(123)
print("int64: " + str(sys.getsizeof(x)))

# int8
x = np.array(123,dtype=np.int8)
print("int8: " + str(sys.getsizeof(x)))

# float32
x = np.array(123,dtype=np.float32)
print("float32: " + str(sys.getsizeof(x)))

int64: 104
int8: 97
float32: 100


## It turns out that there are many computational representation of the same number and you can create arrays with different Data Types (dtypes) depending what you need:

- Boolean : `np.bool_`
- Char : `np.byte`
- Short : `np.short`
- Integer : `np.short`
- Long : `np.int_`
- Float : `np.single`&np.float32`
- Double :`np.double`&`np.float64`
- `np.int8`: integer (-128 to 127)
- `np.int16`:integer( -32768 to 32767)
- `np.int32`: integer(-2147483648 to 2147483647)
- `np.int64`:integer( -9223372036854775808 to 9223372036854775807)


Sometimes, you will need to load, create or export arrays from different data types.


## Harder exercises

The next exercises are related with real situations you could face while you are working in data science and machine learning and we will be frequently talking about matrices and bidimensional arrays.

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [31]:
print("Original matrix:\n")
X = np.random.rand(3, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
print("\nSubtract the mean of each column of the said matrix:\n")
Z = X - X.mean(axis=0, keepdims=True)
print(Z)

Original matrix:

[[0.17872175 0.09772698 0.93534626 0.35651672 0.30417026 0.21461232
  0.02493123 0.06629922 0.62709776 0.18455388]
 [0.9771713  0.66161292 0.3387144  0.77660303 0.86352845 0.19931359
  0.69468815 0.25177744 0.25260386 0.6979448 ]
 [0.26380411 0.63995241 0.48165533 0.31254862 0.16534804 0.46530904
  0.43768727 0.14561645 0.91295726 0.55776905]]

Subtract the mean of each row of the said matrix:

[[-1.20275889e-01 -2.01270663e-01  6.36348627e-01  5.75190827e-02
   5.17262172e-03 -8.43853162e-02 -2.74066411e-01 -2.32698420e-01
   3.28100122e-01 -1.14443754e-01]
 [ 4.05775509e-01  9.02171291e-02 -2.32681395e-01  2.05207236e-01
   2.92132658e-01 -3.72082205e-01  1.23292353e-01 -3.19618351e-01
  -3.18791936e-01  1.26549003e-01]
 [-1.74460650e-01  2.01687654e-01  4.33905691e-02 -1.25716137e-01
  -2.72916720e-01  2.70442830e-02 -5.77486814e-04 -2.92648308e-01
   4.74692505e-01  1.19504290e-01]]

Subtract the mean of each column of the said matrix:

[[-0.29451064 -0.3687038   

#### Exercise: How to get the dates of yesterday, today and tomorrow? (★★☆)
Check `np.datetime64`, `np.timedelta64` in numpy (https://numpy.org/doc/stable/reference/arrays.datetime.html)

In [ ]:
fdhfj

NameError: name 'fdhfj' is not defined

#### Exercise: How to get all the dates corresponding to the month of December 2022? (★★☆)
Combine `arange`with `datetime`


#### Exercise: Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)

#### Exercise: Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### Exercise: Consider a generator function that generates 10 integers and use it to build an array (★★☆)

#### Exercise: Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### Exercise: Create a random vector of size 10 and sort it (★★☆)

#### Exercise: Consider two random array A and B, check if they are equal (★★☆)

#### Exercise: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★★)
Suggestion: check how to calculate the "square of a matrix"

#### Exercise: Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### Exercise: How to print all the values of an array? (★★☆)

#### Exercise: How to convert a float (32 bits) array into an integer (32 bits) in place?
Check https://stackoverflow.com/a/4396247/5989906

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

#### Exercise: How to sort an array by the nth column? (★★☆)

#### Exercise: Find the position of a the minimum of a 2D matrix? (★★☆)

#### Exercise: Read an image using openCV, check its dimensions, normalize the numbers and show the image (★★★)
Check: https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

#### Exercise: Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### Exercise: How to get the diagonal of a dot product? (★★★)

#### Exercise: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### Exercise: How to swap two rows of an array? (★★★)

#### Exercise: Read an image using openCV and tranpose it. What did you get exactly? Was the image rotated? Moved? Reflected with respect to an axis? (★★★)

#### Exercise: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### Exercise: How to find the most frequent value in an array? (★★★)

#### Exercise: How to get the n largest values of an array (★★★)

#### Exercise: Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### Exercise: Given a two dimensional array, how to extract unique rows? (★★★)

#### Exercise: Can you have arrray of strings? can you mix different data types in the same array? Can you operate (add, sub, mult) arrays with different data types? (★★★)