<img src="./assets/numpy_logo.png" alt="logo" width="400"/>

## Introduction to numpy

NumPy stands for 'Numerical Python'. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrices, along with many high-level mathematical functions that operate on these arrays and matrices. It contains among other things:

→ a powerful N-dimensional array object

→ sophisticated (broadcasting) functions

→ tools for integrating C/C++ and Fortran code

→ useful linear algebra, Fourier transform, and random number capabilities

## Installing NumPy
When you want to work with numpy locally, you should run the following commands:

You can install NumPy with:\
`pip install numpy`\
or\
`conda install numpy`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.

## Why should we use NumPy?

Numpy is a library to perform numerical calculation in python. We will use it mainly because it allows us to create and modify matrices, and to do operations on them with ease.

NumPy is, like Pandas, Matplotlib or Scikit-Learn, one of the packages that you cannot miss when you are learning Machine Learning, mainly because this library provides a matrix data structure that has some benefits over regular Python lists. Some of these benefits are: being more compact, quicker access to reading and writing articles, being more convenient and more efficient.

For example, we will see later in the bootcamp that working with images means dealing with three-dimensional matrices as large as 3840 x 2160, which means we will have 3×3840×2160 = 24883200 entries!!! 😱😱😱.

Working with matrices of that magnitude is practically impossible to carry out with lists and dictionaries if one wants to have an efficient and fast programming.

#### Exercise: Import the numpy package under the name `np` (★☆☆)

`numpy` is commonly imported as `np` so we highly recommend to put this alias.

In [1]:
import numpy as np

## What is an array and why it is importante for machine learning?

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.


![alt text](assets/1D.png "1D")

We can have arrays from several dimension. Neural networks sometimes deal with 4D arrays. An array is known as the central data structure of the NumPy library. Array in NumPy is called as NumPy Array. Later, we will use also other kind of arrays thar are called: Tensors.

![alt text](./assets/3D.png "3D")

#### Exercise: Print the numpy version and the configuration (★☆☆)

You can print the version of any package of Python using `name_of_package.__version__`

In [2]:
import numpy as np
print(np.__version__)

1.22.1


#### Exercise: Create a null vector of size 10 (★☆☆)

A `null vector` is an array of zeros (`0`), also called `inicializacion vector`.

Check de function `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise: Create a vector of ones with size 10 (★☆☆)
Check de function `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise: Create an 1D array with specific start value, end value and number of values (★☆☆)

Check the function `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [5]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Run: Create a vector (1D array) with random integers from 10 to 49 and dimension 1x35 (★☆☆)

When `dimension` is expressed `1x35` it means: One dimension array with 35 items (length=35).

Check the function `np.random` which allows you to create random arrays (https://numpy.org/doc/1.16/reference/routines.random.html)

In [6]:
import numpy as np

## 10 random numbers between (0, 1)
print(np.random.random(10))
## 35 random numbers between (10, 49)
print(np.random.random(35)*39 + 10)  

[0.0354507  0.73058862 0.80340723 0.01494075 0.25001978 0.81669266
 0.93658349 0.36853857 0.71214941 0.7459252 ]
[36.35754046 26.21027753 39.57816061 46.03096587 36.67197929 43.01820236
 30.84383263 23.97848882 14.09871519 38.03512818 20.1168376  38.25697938
 22.78351345 39.87752892 21.51521997 41.0420534  25.42529406 16.30594451
 47.02055077 10.18991486 11.00878978 16.11902162 42.66019437 35.69109008
 16.0380205  22.97956791 17.75173537 45.74367083 32.65209886 13.59323107
 26.00814866 48.25244839 47.60890554 44.74373587 12.97261025]


In [7]:
## Two ways to create numbers with normal distribution
print(np.random.rand(10)) # 10 random values with distribution N(0,1)
print(np.random.normal(loc = 0, scale = 1, size = 10)) # 10 random values with distribution N(0,1)

[0.99551518 0.30684401 0.8401608  0.85400645 0.58672324 0.50504516
 0.16199135 0.75063022 0.32601931 0.23905945]
[ 0.43043017 -0.28828383 -0.46827817 -0.65199973 -1.12248233  0.75103147
  0.13192846  0.17749164 -1.22785192 -0.6025981 ]


In [8]:
## Did you notice the difference between both functions? 
print(np.random.normal(loc = -5, scale = 33, size = 10)) # 10 random values with distribution N(-5,33)

[-68.55826538  17.98278988  68.82914787  26.93217496 -26.90459217
 -25.76231318 -27.54448047 -31.38371203 -11.74900771 -18.51677532]


In [9]:
## 10 random values with uniform distribution. That is, all values have the same probability
print(np.random.uniform(-30,100,10)) # All values are between -30 and 100.

[82.0852109  48.18402791 65.37640033  7.21343271  5.64671773 66.63816735
 -5.5746894  21.82783814 56.19797336 90.11312297]


In [10]:
# 10 integers values between 0 and 100.
print(np.random.randint(0, 100, 10))

[85 36 87 41 60 66 36 56 13 13]


In [11]:
# 10 random values with Chi distribution with 5 degrees of freedom
print(np.random.chisquare(5,10))

[12.93955114  1.90654558  3.67375021  4.6533566  10.65364215  6.25261596
  1.93676466  7.76315935  6.43206403  3.15487479]


The above examples are the most common distribution and random values you will learn throughout the bootcamp. Now, let's deal with those arrays.

#### Exercise: Reverse one of the last vector we created before (first element becomes last) (★☆☆)
Try with `[::-1]`

In [12]:
rand_int_vect = np.random.randint(0, 100, 10)
print(rand_int_vect)
print(rand_int_vect[::-1])

[76 70 83 69 71 45 19 56 76 19]
[19 76 56 19 45 71 69 83 70 76]


#### Exercise: Create a 5x5 identidy matrix (★☆☆)
Check the function `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [13]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Exercise: Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
Check the function `where`(https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [14]:
print(np.where(np.array([1,2,0,0,4,0]) != 0)[0])

[0 1 4]


#### Exercise: Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Check the function `min`(https://numpy.org/devdocs/reference/generated/numpy.where.html) and `max`(https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [15]:
arr_10_by_10 = np.random.random((10,10))
print(arr_10_by_10.min())
print(arr_10_by_10.max())

0.003912203278310322
0.997944990214451


#### Exercise: Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
print(np.random.random(30).mean())

0.4931229222717765


#### Exercise: Define a function with input your date of birth (yyyy/mm/dd) that returns a random array with the following dimensions: (★★☆)
$$yyyy-1900 \times |mm - dd|$$

In [17]:
def birth_date(date_of_birth: str) -> np.array:
    date = date_of_birth.split("/")
    size = (int(date[0]) - 1900, np.abs(int(date[1]) - int(date[2])))
    return np.random.random(size) 

birthdate = input("enter your birthday: ")
print(birth_date(birthdate).shape)

(90, 1)


## What is the difference between Python List and a Numpy Array?

- Python list can contain elements with different data types whereas Numpy Array‘s elements are always homogeneous (same data types).
- NumPy arrays are faster and more compact than Python lists.

## Why NumPy Arrays are faster than Lists?

- NumPy Array uses fixed memory to store data and less memory than Python lists.
- Contiguous memory allocation in NumPy Arrays.

#### Exercise: Convert the list `my_list = [1, 2, 3]` to numpy array (★☆☆)

In [18]:
my_list = [1, 2, 3]
numpy_my_list = np.array(my_list)
print(my_list)
print(numpy_my_list)

[1, 2, 3]
[1 2 3]


#### Exercise: Convert the tuple `my_list = (1, 2, 3)` to numpy array (★☆☆)

In [19]:
my_list = (1, 2, 3)
numpy_my_list = np.array(my_list)
print(my_list)
print(numpy_my_list)

(1, 2, 3)
[1 2 3]


#### Exercise: Convert the list of tuples `my_list = [(1,2,3), (4,5)]` to numpy array (★☆☆)

In [20]:
my_list = [(1, 2, 3), (4,5)]
numpy_my_list = np.array(my_list, dtype=np.ndarray)
print(my_list)
print(numpy_my_list)

[(1, 2, 3), (4, 5)]
[(1, 2, 3) (4, 5)]


#### Exercise: Resize a random array of dimensions 5x12 into 12x5 (★☆☆)
Check `reshape`from `numpy`(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [21]:
size1 = 5,12
size2 = 12,5
arr1 = np.random.random(size1)
arr2 = arr1.reshape(size2)
print(arr1.shape)
print(arr2.shape)

(5, 12)
(12, 5)


#### Exercise: Create a function that normalize a 5x5 random matrix (★☆☆)
Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :
$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$


In [22]:
arr_to_normalize = np.random.random((5,5))
arr_normalized = (arr_to_normalize - arr_to_normalize.mean()) / arr_to_normalize.std()
print(arr_normalized)

[[ 0.26206524 -0.93722089 -0.20302179 -0.27350592  1.04760971]
 [-1.47358015 -1.08576979 -0.52128582  0.52943607  1.57356964]
 [-0.78792821  1.37552727 -0.551378   -1.21116913  0.74809006]
 [ 1.38458861 -0.57477121  0.04469699  1.28271305 -0.46337531]
 [ 1.43651497 -1.44785493 -0.57740816  1.42106884 -0.99761114]]


## Stacking numpy arrays

Stacking is used to join a sequence of same dimension arrays along a new axis.
`numpy.stack(arrays,axis)` : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

### You have two ways to do it:


![alt text](./assets/stack.jpeg "stack")


### or


![alt text](./assets/stack2.jpeg "stack")




#### Exercise: Generate two random arrays with integers and apply the stacking using `stack` (★★☆)

In [23]:
arr_1 = np.random.randint(0, 10, (2,2))
arr_2 = np.random.randint(0, 10, (2,2))
print(arr_1)
print()
print(arr_2)
print()
print(np.stack((arr_1, arr_2)))

[[7 7]
 [6 3]]

[[6 5]
 [8 3]]

[[[7 7]
  [6 3]]

 [[6 5]
  [8 3]]]


#### Exercise: Generate two random arrays with integers and apply the stacking using `hstack` and `vstack` (★★☆)

In [24]:
arr_1 = np.random.randint(0, 10, (2,2))
arr_2 = np.random.randint(0, 10, (2,2))
print(arr_1)
print()
print(arr_2)
print()
print(np.hstack((arr_1, arr_2)))
print()
print(np.vstack((arr_1, arr_2)))

[[7 5]
 [9 2]]

[[7 9]
 [2 4]]

[[7 5 7 9]
 [9 2 2 4]]

[[7 5]
 [9 2]
 [7 9]
 [2 4]]


## Basic maths in numpy

You can make typical math operations like:

- Addition,Subtraction,Multiplication and Division between two arrays using numpy.
- Operation on array using sum() & cumsum() function.
- Minimum and Maximum value from an array
- Exponent/Power , Square Root and Cube Root functions

or even apply common trigonometric functions:

- `numpy.sin()`:  Sine (x) Function
- `numpy.cos()`: Cosine(x) Function
- `numpy.tan()`: Tangent(x)Function
- `numpy.sinh()`: Hyperbolic Sine (x) Function
- `numpy.cosh()`: Hyperbolic Cosine(x) Functionv
- `numpy.tanh()`: Hyperbolic Tangent(x)Function
- `numpy.arcsin()`: Inverse Sine Function
- `numpy.arccos()`: Inverse Cosine Function
- `numpy.arctan()`: Inverse Tangent Function
- `numpy.pi`: pi value
- `numpy.hypot(w,h)`: For calculating Hypotenuse $c = \sqrt{(w^2 + h^2)}$
- `numpy.rad2deg()`: Radians to degrees
- `numpy.deg2rad()`: Degrees to radians

#### Exercise: Generate two random 8 - dimensional vectors and apply the most common operation between vectors:  addition, substraction, multiplication, division(★☆☆)

Check the math functions here: https://numpy.org/doc/stable/reference/routines.math.html

In [25]:
vect_1 = np.random.random(8)
vect_2 = np.random.random(8)

print(vect_1 + vect_2)
print(vect_1 - vect_2)
print(vect_1 * vect_2)
print(vect_1 / vect_2)

[0.63988405 1.02020287 1.27540614 0.54063102 1.15049569 1.14760029
 0.15681581 0.93985285]
[ 0.29405244 -0.11174437 -0.6775999   0.42013457  0.08401265 -0.20922317
 -0.14569876  0.09000385]
[0.08074619 0.25708177 0.2918798  0.02894221 0.32914555 0.31830302
 0.00084077 0.21880567]
[2.70055265 0.80256258 0.30609544 7.97339307 1.15755084 0.69159853
 0.03674881 1.21181138]


#### Exercise: Generate two random matrices with dimensions between 5 and 10, e.g. 5x7 vs 8x9 and try. Were you able to do the matrix multiplication? why? (★★☆) 

In [26]:
matrix_1 = np.random.random((np.random.randint(5,10), np.random.randint(5,10)))
matrix_2 = np.random.random((np.random.randint(5,10), np.random.randint(5,10)))


#print(matrix_1 * matrix_2) #ValueError: operands could not be broadcast together with shapes (9,7) (6,5) 

#### Exercise: Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array) Were you able to do the matrix multiplication? (★★☆) 

$$ a = \left(\begin{matrix}
0 & 1 & 2\\ 
3 & 4 & 5\\ 
6 & 7 & 8
\end{matrix}\right)$$

$$ b = \left(\begin{matrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{matrix}\right)$$




In [27]:
a = np.linspace(0, 8, 9).reshape((3,3))
b = np.linspace(2, 10, 9).reshape((3,3))
print(a)
print(b)
print(a * b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 0.  3.  8.]
 [15. 24. 35.]
 [48. 63. 80.]]


#### Exercise: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★★☆)

In [28]:
matrix_1 = np.random.random((5, 3))
matrix_2 = np.random.random((3, 2))

print(np.dot(matrix_1, matrix_2))

[[0.41992641 0.99767641]
 [0.64275001 0.77766174]
 [0.17189701 0.20581045]
 [0.59821238 0.96304079]
 [0.27722084 0.76427032]]


## Data types

Do you think the following preposition is true?
`8==8`

Surely you will definetely say yes, which is true mathematically, but computationally it is not always the same, at least in terms of memory. For example, run the following cell:

In [29]:
import sys

# int64
x = np.array(123)
print("int64: " + str(sys.getsizeof(x)))

# int8
x = np.array(123,dtype=np.int8)
print("int8: " + str(sys.getsizeof(x)))

# float32
x = np.array(123,dtype=np.float32)
print("float32: " + str(sys.getsizeof(x)))

int64: 104
int8: 97
float32: 100


## It turns out that there are many computational representation of the same number and you can create arrays with different Data Types (dtypes) depending what you need:

- Boolean : `np.bool_`
- Char : `np.byte`
- Short : `np.short`
- Integer : `np.short`
- Long : `np.int_`
- Float : `np.single`&np.float32`
- Double :`np.double`&`np.float64`
- `np.int8`: integer (-128 to 127)
- `np.int16`:integer( -32768 to 32767)
- `np.int32`: integer(-2147483648 to 2147483647)
- `np.int64`:integer( -9223372036854775808 to 9223372036854775807)


Sometimes, you will need to load, create or export arrays from different data types.


## Harder exercises

The next exercises are related with real situations you could face while you are working in data science and machine learning and we will be frequently talking about matrices and bidimensional arrays.

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [30]:
print("Original matrix:\n")
X = np.random.rand(3, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
print("\nSubtract the mean of each column of the said matrix:\n")
Z = X - X.mean(axis=0, keepdims=True)
print(Z)

Original matrix:

[[0.71189443 0.41860722 0.5378022  0.7012617  0.10403333 0.30537157
  0.45553436 0.27871    0.72688948 0.05144641]
 [0.12387409 0.42769069 0.3018106  0.8042094  0.93111272 0.19247362
  0.19398284 0.13237162 0.894996   0.15732187]
 [0.13700133 0.43536869 0.50386553 0.80028273 0.6712112  0.81659511
  0.36805158 0.46761923 0.56951425 0.44978445]]

Subtract the mean of each row of the said matrix:

[[ 0.28273936 -0.01054785  0.10864712  0.27210663 -0.32512174 -0.1237835
   0.02637929 -0.15044507  0.29773441 -0.37770866]
 [-0.29211025  0.01170635 -0.11417375  0.38822506  0.51512838 -0.22351073
  -0.22200151 -0.28361272  0.47901165 -0.25866247]
 [-0.38492808 -0.08656072 -0.01806388  0.27835332  0.14928179  0.2946657
  -0.15387783 -0.05431018  0.04758485 -0.07214496]]

Subtract the mean of each column of the said matrix:

[[ 0.38763782 -0.00861498  0.08997609 -0.06732291 -0.46475242 -0.13277519
   0.11634477 -0.01419029 -0.0035771  -0.16807117]
 [-0.20038252  0.00046849 -0.1

#### Exercise: How to get the dates of yesterday, today and tomorrow? (★★☆)
Check `np.datetime64`, `np.timedelta64` in numpy (https://numpy.org/doc/stable/reference/arrays.datetime.html)

In [31]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("today", today)
print("yesterday", yesterday)
print("tomorrow", tomorrow)

today 2022-01-19
yesterday 2022-01-18
tomorrow 2022-01-20


#### Exercise: How to get all the dates corresponding to the month of December 2022? (★★☆)
Combine `arange`with `datetime`


In [32]:
all_dates_solution1 = [(np.datetime64('2022-12', 'D') + np.timedelta64(day, 'D')).astype("str") for day in np.arange(31)]
all_dates_solution2 = np.arange('2022-12', '2023-01', dtype='datetime64[D]')
print(all_dates_solution1)
print(all_dates_solution2)


['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06', '2022-12-07', '2022-12-08', '2022-12-09', '2022-12-10', '2022-12-11', '2022-12-12', '2022-12-13', '2022-12-14', '2022-12-15', '2022-12-16', '2022-12-17', '2022-12-18', '2022-12-19', '2022-12-20', '2022-12-21', '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25', '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29', '2022-12-30', '2022-12-31']
['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
 '2022-12-06' '2022-12-07' '2022-12-08' '2022-12-09' '2022-12-10'
 '2022-12-11' '2022-12-12' '2022-12-13' '2022-12-14' '2022-12-15'
 '2022-12-16' '2022-12-17' '2022-12-18' '2022-12-19' '2022-12-20'
 '2022-12-21' '2022-12-22' '2022-12-23' '2022-12-24' '2022-12-25'
 '2022-12-26' '2022-12-27' '2022-12-28' '2022-12-29' '2022-12-30'
 '2022-12-31']


#### Exercise: Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)

In [33]:
arr_random_1 = np.random.rand(10) * 10
print(arr_random_1.astype("int"))
print(np.int64(arr_random_1))


[2 3 4 4 2 0 7 8 4 0]
[2 3 4 4 2 0 7 8 4 0]


#### Exercise: Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [34]:
m_5x5 = np.int64(np.random.rand(5,5) * 4)
print(m_5x5)

[[3 0 2 1 3]
 [2 0 2 3 0]
 [2 2 1 2 2]
 [2 3 3 0 1]
 [2 2 1 0 0]]


#### Exercise: Consider a generator function that generates 10 integers and use it to build an array (★★☆)

In [35]:
def generate():
   for n in range(10):
       yield n
gen_arr_10int = np.fromiter(generate(),dtype=int)

print(gen_arr_10int)

[0 1 2 3 4 5 6 7 8 9]


#### Exercise: Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [36]:
print(np.linspace(0,1,10)[1:-1])

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


#### Exercise: Create a random vector of size 10 and sort it (★★☆)

In [37]:
print(np.sort(np.random.rand(10)))

[0.04802911 0.12303888 0.14519183 0.33526817 0.35733617 0.36201969
 0.50166157 0.67127279 0.86503097 0.96864331]


#### Exercise: Consider two random array A and B, check if they are equal (★★☆)

In [38]:
A = np.random.rand(2,10)
B = np.random.rand(2,10)
print(np.allclose(A, B))
print(np.isclose(A, B))
##print(np.all(A, B)) # only integer scalar arrays
##print(np.any(A, B)) # only integer scalar arrays
print(np.equal(A, B))
print(A == B)


False
[[False False False False False False False False False False]
 [False False False False False False False False False False]]
[[False False False False False False False False False False]
 [False False False False False False False False False False]]
[[False False False False False False False False False False]
 [False False False False False False False False False False]]


#### Exercise: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★★)
Suggestion: check how to calculate the "square of a matrix"

In [39]:
cartesian_coordinates = np.random.rand(10,2)
print(cartesian_coordinates)
#print(np.arctan(cartesian_coordinates[:,1]/cartesian_coordinates[:,0]).reshape(-1,1))
#print(np.sqrt((cartesian_coordinates[:,1])**2 + (cartesian_coordinates[:,0])**2).reshape(-1,1))
polar_coordinates = np.array([np.sqrt((cartesian_coordinates[:,0])**2 + (cartesian_coordinates[:,1])**2), np.arctan(cartesian_coordinates[:,1]/cartesian_coordinates[:,0])])
print(polar_coordinates.reshape(10,2))


[[0.65758425 0.23473058]
 [0.9319529  0.01360885]
 [0.78488743 0.82372443]
 [0.53565051 0.2351396 ]
 [0.96812922 0.67477341]
 [0.87678383 0.88005282]
 [0.56251639 0.48230074]
 [0.69950846 0.5354584 ]
 [0.89841262 0.95372431]
 [0.40523199 0.43485244]]
[[0.69822309 0.93205225]
 [1.13779181 0.58498897]
 [1.18008192 1.24227326]
 [0.74097145 0.88092439]
 [1.31024246 0.59439853]
 [0.34286083 0.01460147]
 [0.80953665 0.41365159]
 [0.6087009  0.78725889]
 [0.70877365 0.65333372]
 [0.815253   0.82064245]]


#### Exercise: Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [40]:
rand_vect = np.random.randint(1,20,size=10)
print(rand_vect)
print(rand_vect.max())
rand_vect[rand_vect == rand_vect.max()]=0
print(rand_vect)

[ 3 15 19  5  6  2 10 10 14  4]
19
[ 3 15  0  5  6  2 10 10 14  4]


#### Exercise: How to print all the values of an array? (★★☆)

In [41]:
rand_vect = np.random.rand(12,20)*20 + 3

with np.printoptions(threshold=np.inf):
    print(rand_vect)
print(rand_vect.tolist())

[[ 7.81051338  4.72045391 15.73059867 17.40593905 16.82892116  9.53263297
  19.33950657 13.15085148 15.4934064   9.3395598  20.56590276 15.0894289
   9.42644127 15.55258271 15.94959077 12.73036856  6.16703867 14.36342597
   5.47855807 14.54784654]
 [21.30241124 10.9258153   4.91282218  8.32590792 17.00377213 13.54676233
  19.2346715   3.18806312 13.92173988 19.80199871 20.30215241 17.24904204
   8.5131875   7.58710294 12.97591416 18.8960211   7.08130365 13.74581757
  11.53626957  7.8324196 ]
 [17.6409501   9.05829758  9.79117381 14.80939403 20.59759588 22.27043549
  21.55777128  8.06294413 22.11398955 17.59906128  9.09510414  5.53670604
  15.52655074  8.39152008 21.22273088 14.38586865 10.92570131  7.51937366
  15.64447885 17.52664388]
 [ 5.19730839 13.35590732 10.78639107 16.55273363 20.84749031 22.24976773
  20.96202133  3.5123652  12.93499603 12.67152836 21.73556663 22.26356854
  16.22477649 13.1334382  21.4244707  10.18557085  4.37182385 10.91969414
  14.75488102  9.1979761 ]
 [13.

#### Exercise: How to convert a float (32 bits) array into an integer (32 bits) in place?
Check https://stackoverflow.com/a/4396247/5989906

In [42]:
rand_vect = np.random.rand(12,20).astype(np.float32) *20 + 3
y = rand_vect.view('int32')
y[:] = rand_vect
print(y)

[[11 14 20 12 16 20 16 14 20 15 11  9 12  6 10  9 18 18  8  6]
 [19  5  8 14 22 17 16  3 20 21 18  6  3 15  7 18 20 14 20 12]
 [15 15 20 20  9 16  6  6  3  3 13  6 21 16  5 16 10 10  6 17]
 [11 19  9 15 18  6 15 14  7 22  3 15 21  9 17  4  8 18 17 21]
 [ 4  6 12 19 13  5 20 22 19 18 12 16 11 14  5  6 15 21 21 15]
 [ 9 13  3 13  3  4 20 21  6 17 22 15 13 13  7 21  8 22  8  8]
 [21 12  4 17 22  7 10  5 19  9  5 12 14 11 18 14 12  7  5  4]
 [15 12 18 14 15 17 16 21  5 22  9  7 11  8 12  4 15  6 16 12]
 [17 21 16 19  8  9 16 16 18 13 19 12 22 22 22 19 11  4 11  4]
 [13  8 19 18 21 16  7 19 20 19  7  3 17  3  3  6 20  4 13  5]
 [13  7 20 19 10  7 17 22 11 16 13  7 20 19 19 21  4 18 11 16]
 [ 7 19 11 22 16 12 11 10 19 12 12 10 12 16 18 20 22 10  4 17]]


#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [94]:
mtx_a = np.random.randint(1,20,size=(3,3))
print(mtx_a)
print(mtx_a.mean(axis=1))
print(mtx_a - mtx_a.mean(axis=1).reshape(-1,1))
print(mtx_a - mtx_a.mean(axis=1, keepdims=True))

[[14 13 15]
 [16  4  3]
 [12  2  1]]
[14.          7.66666667  5.        ]
[[ 0.         -1.          1.        ]
 [ 8.33333333 -3.66666667 -4.66666667]
 [ 7.         -3.         -4.        ]]
[[ 0.         -1.          1.        ]
 [ 8.33333333 -3.66666667 -4.66666667]
 [ 7.         -3.         -4.        ]]


#### Exercise: How to sort an array by the nth column? (★★☆)

In [95]:
mtx_a = np.random.randint(1,20,size=(3,5))
print(mtx_a)
print()
#mtx_a = mtx_a.tolist()
cols = [1]
print(mtx_a[np.lexsort(mtx_a.T[cols])])
print()
print(mtx_a[ mtx_a[:,1].argsort()])
print(mtx_a[ mtx_a[:,1].argsort(),:])
mtx_a.view('i8,i8,i8,i8,i8').sort(order=['f1'], axis=0)
print(mtx_a)


[[10  3  4 15 12]
 [ 1  5 15 10 18]
 [ 1  3 16  9 19]]

[[10  3  4 15 12]
 [ 1  3 16  9 19]
 [ 1  5 15 10 18]]

[[10  3  4 15 12]
 [ 1  3 16  9 19]
 [ 1  5 15 10 18]]
[[10  3  4 15 12]
 [ 1  3 16  9 19]
 [ 1  5 15 10 18]]
[[ 1  3 16  9 19]
 [10  3  4 15 12]
 [ 1  5 15 10 18]]


#### Exercise: Find the position of a the minimum of a 2D matrix? (★★☆)

#### Exercise: Read an image using openCV, check its dimensions, normalize the numbers and show the image (★★★)
Check: https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

#### Exercise: Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### Exercise: How to get the diagonal of a dot product? (★★★)

#### Exercise: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### Exercise: How to swap two rows of an array? (★★★)

#### Exercise: Read an image using openCV and tranpose it. What did you get exactly? Was the image rotated? Moved? Reflected with respect to an axis? (★★★)

#### Exercise: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### Exercise: How to find the most frequent value in an array? (★★★)

#### Exercise: How to get the n largest values of an array (★★★)

#### Exercise: Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### Exercise: Given a two dimensional array, how to extract unique rows? (★★★)

#### Exercise: Can you have arrray of strings? can you mix different data types in the same array? Can you operate (add, sub, mult) arrays with different data types? (★★★)