<img src="./assets/numpy_logo.png" alt="logo" width="400"/>

## Introduction to numpy

NumPy stands for 'Numerical Python'. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrices, along with many high-level mathematical functions that operate on these arrays and matrices. It contains among other things:

→ a powerful N-dimensional array object

→ sophisticated (broadcasting) functions

→ tools for integrating C/C++ and Fortran code

→ useful linear algebra, Fourier transform, and random number capabilities

## Installing NumPy
When you want to work with numpy locally, you should run the following commands:

You can install NumPy with:\
`pip install numpy`\
or\
`conda install numpy`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.

## Why should we use NumPy?

Numpy is a library to perform numerical calculation in python. We will use it mainly because it allows us to create and modify matrices, and to do operations on them with ease.

NumPy is, like Pandas, Matplotlib or Scikit-Learn, one of the packages that you cannot miss when you are learning Machine Learning, mainly because this library provides a matrix data structure that has some benefits over regular Python lists. Some of these benefits are: being more compact, quicker access to reading and writing articles, being more convenient and more efficient.

For example, we will see later in the bootcamp that working with images means dealing with three-dimensional matrices as large as 3840 x 2160, which means we will have 3×3840×2160 = 24883200 entries!!! 😱😱😱.

Working with matrices of that magnitude is practically impossible to carry out with lists and dictionaries if one wants to have an efficient and fast programming.

#### Exercise: Import the numpy package under the name `np` (★☆☆)

`numpy` is commonly imported as `np` so we highly recommend to put this alias.

In [206]:
import numpy as np

## What is an array and why it is importante for machine learning?

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.


![alt text](assets/1D.png "1D")

We can have arrays from several dimension. Neural networks sometimes deal with 4D arrays. An array is known as the central data structure of the NumPy library. Array in NumPy is called as NumPy Array. Later, we will use also other kind of arrays thar are called: Tensors.

![alt text](./assets/3D.png "3D")

#### Exercise: Print the numpy version and the configuration (★☆☆)

You can print the version of any package of Python using `name_of_package.__version__`

In [207]:
import numpy as np
print(np.__version__)

1.22.1


#### Exercise: Create a null vector of size 10 (★☆☆)

A `null vector` is an array of zeros (`0`), also called `inicializacion vector`.

Check de function `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [208]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise: Create a vector of ones with size 10 (★☆☆)
Check de function `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [209]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise: Create an 1D array with specific start value, end value and number of values (★☆☆)

Check the function `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [210]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Run: Create a vector (1D array) with random integers from 10 to 49 and dimension 1x35 (★☆☆)

When `dimension` is expressed `1x35` it means: One dimension array with 35 items (length=35).

Check the function `np.random` which allows you to create random arrays (https://numpy.org/doc/1.16/reference/routines.random.html)

In [211]:
import numpy as np

## 10 random numbers between (0, 1)
print(np.random.random(10))
## 35 random numbers between (10, 49)
print(np.random.random(35)*39 + 10)  

[0.29694163 0.27233565 0.5471662  0.60602142 0.19275901 0.83551488
 0.7049453  0.84954637 0.98674651 0.11358705]
[34.77974449 25.91050527 21.21144056 17.85030686 26.67844262 11.37048247
 21.84141188 17.50623564 25.02951386 47.00984482 42.14652652 45.8054234
 39.90042882 23.93550854 43.89157885 22.52335504 25.42241673 18.40162335
 38.65241785 28.77627136 42.8040446  47.29930943 35.97665506 33.04017564
 16.91228507 21.31290666 40.91177564 10.09120353 16.2831027  38.73706506
 29.88185189 30.40885547 26.26844895 28.88807928 16.91950594]


In [212]:
## Two ways to create numbers with normal distribution
print(np.random.rand(10)) # 10 random values with distribution N(0,1)
print(np.random.normal(loc = 0, scale = 1, size = 10)) # 10 random values with distribution N(0,1)

[0.53745395 0.93063004 0.40304317 0.09531237 0.65120336 0.05337763
 0.79700264 0.2589636  0.79528834 0.14958711]
[ 8.99055667e-01  1.87319045e-01 -1.41790194e-01  4.42842172e-01
  1.15016563e+00 -1.58188523e-01 -1.30341990e-04 -6.16686041e-01
 -5.54779157e-01  9.83327864e-01]


In [213]:
## Did you notice the difference between both functions? 
print(np.random.normal(loc = -5, scale = 33, size = 10)) # 10 random values with distribution N(-5,33)

[-47.90807081  -0.83050994  -8.88055518  23.29589629 -41.65253204
 -17.72173138 -27.84773421 -27.15520311  15.24751395  32.12364833]


In [214]:
## 10 random values with uniform distribution. That is, all values have the same probability
print(np.random.uniform(-30,100,10)) # All values are between -30 and 100.

[65.03333237 40.1431204  22.34293825 60.15175927 16.9731744  -2.24292208
 34.83417952 50.63005443 33.86773946 -5.91170996]


In [215]:
# 10 integers values between 0 and 100.
print(np.random.randint(0, 100, 10))

[95 60 24 35 21 60 52 82 62 80]


In [216]:
# 10 random values with Chi distribution with 5 degrees of freedom
print(np.random.chisquare(5,10))

[1.68123836 9.34662487 5.15897303 0.9360501  3.46373272 4.87896166
 1.62530303 5.63492677 9.33068713 2.67399479]


The above examples are the most common distribution and random values you will learn throughout the bootcamp. Now, let's deal with those arrays.

#### Exercise: Reverse one of the last vector we created before (first element becomes last) (★☆☆)
Try with `[::-1]`

In [217]:
rand_int_vect = np.random.randint(0, 100, 10)
print(rand_int_vect)
print(rand_int_vect[::-1])

[25 58 33 92  6 92 95 19 18 92]
[92 18 19 95 92  6 92 33 58 25]


#### Exercise: Create a 5x5 identidy matrix (★☆☆)
Check the function `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [218]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Exercise: Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
Check the function `where`(https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [219]:
print(np.where(np.array([1,2,0,0,4,0]) != 0)[0])

[0 1 4]


#### Exercise: Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Check the function `min`(https://numpy.org/devdocs/reference/generated/numpy.where.html) and `max`(https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [220]:
arr_10_by_10 = np.random.random((10,10))
print(arr_10_by_10.min())
print(arr_10_by_10.max())

0.0032350827273522897
0.9944193320577756


#### Exercise: Create a random vector of size 30 and find the mean value (★☆☆)

In [221]:
print(np.random.random(30).mean())

0.46894231169730105


#### Exercise: Define a function with input your date of birth (yyyy/mm/dd) that returns a random array with the following dimensions: (★★☆)
$$yyyy-1900 \times |mm - dd|$$

In [222]:
def birth_date(date_of_birth: str) -> np.array:
    date = date_of_birth.split("/")
    size = (int(date[0]) - 1900, np.abs(int(date[1]) - int(date[2])))
    return np.random.random(size) 

birthdate = input("enter your birthday: ")
print(birth_date(birthdate).shape)

(90, 1)


## What is the difference between Python List and a Numpy Array?

- Python list can contain elements with different data types whereas Numpy Array‘s elements are always homogeneous (same data types).
- NumPy arrays are faster and more compact than Python lists.

## Why NumPy Arrays are faster than Lists?

- NumPy Array uses fixed memory to store data and less memory than Python lists.
- Contiguous memory allocation in NumPy Arrays.

#### Exercise: Convert the list `my_list = [1, 2, 3]` to numpy array (★☆☆)

In [223]:
my_list = [1, 2, 3]
numpy_my_list = np.array(my_list)
print(my_list)
print(numpy_my_list)

[1, 2, 3]
[1 2 3]


#### Exercise: Convert the tuple `my_list = (1, 2, 3)` to numpy array (★☆☆)

In [224]:
my_list = (1, 2, 3)
numpy_my_list = np.array(my_list)
print(my_list)
print(numpy_my_list)

(1, 2, 3)
[1 2 3]


#### Exercise: Convert the list of tuples `my_list = [(1,2,3), (4,5)]` to numpy array (★☆☆)

In [225]:
my_list = [(1, 2, 3), (4,5)]
numpy_my_list = np.array(my_list, dtype=np.ndarray)
print(my_list)
print(numpy_my_list)

[(1, 2, 3), (4, 5)]
[(1, 2, 3) (4, 5)]


#### Exercise: Resize a random array of dimensions 5x12 into 12x5 (★☆☆)
Check `reshape`from `numpy`(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [226]:
size1 = 5,12
size2 = 12,5
arr1 = np.random.random(size1)
arr2 = arr1.reshape(size2)
print(arr1.shape)
print(arr2.shape)

(5, 12)
(12, 5)


#### Exercise: Create a function that normalize a 5x5 random matrix (★☆☆)
Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :
$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$


In [227]:
arr_to_normalize = np.random.random((5,5))
arr_normalized = (arr_to_normalize - arr_to_normalize.mean()) / arr_to_normalize.std()
print(arr_normalized)

[[-1.00694198 -0.1059257  -1.00387981  1.29214783  0.51888693]
 [ 0.57001946 -0.81122672 -1.35184389  0.4427041  -0.5568541 ]
 [-1.25118492 -0.22667817  1.49121738  1.48428965 -0.97521924]
 [ 1.44988498  1.18169928  1.36939591 -0.95309295 -1.48863906]
 [ 1.03742667 -0.4633371  -0.87298918 -0.14864122  0.37878185]]


## Stacking numpy arrays

Stacking is used to join a sequence of same dimension arrays along a new axis.
`numpy.stack(arrays,axis)` : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

### You have two ways to do it:


![alt text](./assets/stack.jpeg "stack")


### or


![alt text](./assets/stack2.jpeg "stack")




#### Exercise: Generate two random arrays with integers and apply the stacking using `stack` (★★☆)

In [228]:
arr_1 = np.random.randint(0, 10, (2,2))
arr_2 = np.random.randint(0, 10, (2,2))
print(arr_1)
print()
print(arr_2)
print()
print(np.stack((arr_1, arr_2)))

[[1 5]
 [7 0]]

[[7 8]
 [7 2]]

[[[1 5]
  [7 0]]

 [[7 8]
  [7 2]]]


#### Exercise: Generate two random arrays with integers and apply the stacking using `hstack` and `vstack` (★★☆)

In [229]:
arr_1 = np.random.randint(0, 10, (2,2))
arr_2 = np.random.randint(0, 10, (2,2))
print(arr_1)
print()
print(arr_2)
print()
print(np.hstack((arr_1, arr_2)))
print()
print(np.vstack((arr_1, arr_2)))

[[1 4]
 [9 3]]

[[1 2]
 [0 6]]

[[1 4 1 2]
 [9 3 0 6]]

[[1 4]
 [9 3]
 [1 2]
 [0 6]]


## Basic maths in numpy

You can make typical math operations like:

- Addition,Subtraction,Multiplication and Division between two arrays using numpy.
- Operation on array using sum() & cumsum() function.
- Minimum and Maximum value from an array
- Exponent/Power , Square Root and Cube Root functions

or even apply common trigonometric functions:

- `numpy.sin()`:  Sine (x) Function
- `numpy.cos()`: Cosine(x) Function
- `numpy.tan()`: Tangent(x)Function
- `numpy.sinh()`: Hyperbolic Sine (x) Function
- `numpy.cosh()`: Hyperbolic Cosine(x) Functionv
- `numpy.tanh()`: Hyperbolic Tangent(x)Function
- `numpy.arcsin()`: Inverse Sine Function
- `numpy.arccos()`: Inverse Cosine Function
- `numpy.arctan()`: Inverse Tangent Function
- `numpy.pi`: pi value
- `numpy.hypot(w,h)`: For calculating Hypotenuse $c = \sqrt{(w^2 + h^2)}$
- `numpy.rad2deg()`: Radians to degrees
- `numpy.deg2rad()`: Degrees to radians

#### Exercise: Generate two random 8 - dimensional vectors and apply the most common operation between vectors:  addition, substraction, multiplication, division(★☆☆)

Check the math functions here: https://numpy.org/doc/stable/reference/routines.math.html

In [230]:
vect_1 = np.random.random(8)
vect_2 = np.random.random(8)

print(vect_1 + vect_2)
print(vect_1 - vect_2)
print(vect_1 * vect_2)
print(vect_1 / vect_2)

[1.11030894 1.11476108 1.77967041 0.85072714 0.54100433 1.05093989
 0.93945148 1.34209756]
[-0.17831038 -0.2680988  -0.14342169  0.78183845  0.14387107  0.79396567
  0.32117848 -0.35575026]
[0.30024784 0.29270383 0.78666424 0.02811633 0.0679967  0.11852329
 0.19485337 0.4186669 ]
[ 0.7232536   0.61225456  0.85084262 23.69859814  1.72454807  7.17934097
  2.0389536   0.58093976]


#### Exercise: Generate two random matrices with dimensions between 5 and 10, e.g. 5x7 vs 8x9 and try. Were you able to do the matrix multiplication? why? (★★☆) 

In [231]:
matrix_1 = np.random.random((np.random.randint(5,10), np.random.randint(5,10)))
matrix_2 = np.random.random((np.random.randint(5,10), np.random.randint(5,10)))


#print(matrix_1 * matrix_2) #ValueError: operands could not be broadcast together with shapes (9,7) (6,5) 

#### Exercise: Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array) Were you able to do the matrix multiplication? (★★☆) 

$$ a = \left(\begin{matrix}
0 & 1 & 2\\ 
3 & 4 & 5\\ 
6 & 7 & 8
\end{matrix}\right)$$

$$ b = \left(\begin{matrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{matrix}\right)$$




In [232]:
a = np.linspace(0, 8, 9).reshape((3,3))
b = np.linspace(2, 10, 9).reshape((3,3))
print(a)
print(b)
print(a * b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 0.  3.  8.]
 [15. 24. 35.]
 [48. 63. 80.]]


#### Exercise: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★★☆)

In [233]:
matrix_1 = np.random.random((5, 3))
matrix_2 = np.random.random((3, 2))

print(np.dot(matrix_1, matrix_2))

[[0.99406736 1.07483836]
 [1.05797512 0.90881838]
 [0.62512376 0.99850683]
 [0.77213388 0.82508064]
 [0.58871615 0.53584658]]


## Data types

Do you think the following preposition is true?
`8==8`

Surely you will definetely say yes, which is true mathematically, but computationally it is not always the same, at least in terms of memory. For example, run the following cell:

In [234]:
import sys

# int64
x = np.array(123)
print("int64: " + str(sys.getsizeof(x)))

# int8
x = np.array(123,dtype=np.int8)
print("int8: " + str(sys.getsizeof(x)))

# float32
x = np.array(123,dtype=np.float32)
print("float32: " + str(sys.getsizeof(x)))

int64: 104
int8: 97
float32: 100


## It turns out that there are many computational representation of the same number and you can create arrays with different Data Types (dtypes) depending what you need:

- Boolean : `np.bool_`
- Char : `np.byte`
- Short : `np.short`
- Integer : `np.short`
- Long : `np.int_`
- Float : `np.single`&np.float32`
- Double :`np.double`&`np.float64`
- `np.int8`: integer (-128 to 127)
- `np.int16`:integer( -32768 to 32767)
- `np.int32`: integer(-2147483648 to 2147483647)
- `np.int64`:integer( -9223372036854775808 to 9223372036854775807)


Sometimes, you will need to load, create or export arrays from different data types.


## Harder exercises

The next exercises are related with real situations you could face while you are working in data science and machine learning and we will be frequently talking about matrices and bidimensional arrays.

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [235]:
print("Original matrix:\n")
X = np.random.rand(3, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
print("\nSubtract the mean of each column of the said matrix:\n")
Z = X - X.mean(axis=0, keepdims=True)
print(Z)

Original matrix:

[[0.09818499 0.65513746 0.65239968 0.3220984  0.59615442 0.86033415
  0.38643628 0.07669069 0.71942906 0.29681537]
 [0.04036457 0.28334365 0.81525575 0.90644491 0.76294889 0.48586585
  0.60215713 0.48440519 0.17691711 0.76810888]
 [0.62937957 0.07586162 0.35582462 0.72659685 0.12487158 0.17176453
  0.92830191 0.40745322 0.50896293 0.85602775]]

Subtract the mean of each row of the said matrix:

[[-0.36818306  0.18876941  0.18603163 -0.14426965  0.12978637  0.3939661
  -0.07993177 -0.38967736  0.25306101 -0.16955268]
 [-0.49221662 -0.24923754  0.28267456  0.37386372  0.2303677  -0.04671534
   0.06957594 -0.048176   -0.35566408  0.23552768]
 [ 0.15087511 -0.40264284 -0.12267984  0.24809239 -0.35363288 -0.30673993
   0.44979746 -0.07105124  0.03045847  0.37752329]]

Subtract the mean of each column of the said matrix:

[[-0.15779139  0.31702322  0.044573   -0.32961498  0.10149612  0.35434597
  -0.25252883 -0.24615901  0.25099269 -0.34350196]
 [-0.21561181 -0.0547706   0.

#### Exercise: How to get the dates of yesterday, today and tomorrow? (★★☆)
Check `np.datetime64`, `np.timedelta64` in numpy (https://numpy.org/doc/stable/reference/arrays.datetime.html)

In [236]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("today", today)
print("yesterday", yesterday)
print("tomorrow", tomorrow)

today 2022-01-20
yesterday 2022-01-19
tomorrow 2022-01-21


#### Exercise: How to get all the dates corresponding to the month of December 2022? (★★☆)
Combine `arange`with `datetime`


In [237]:
all_dates_solution1 = [(np.datetime64('2022-12', 'D') + np.timedelta64(day, 'D')).astype("str") for day in np.arange(31)]
all_dates_solution2 = np.arange('2022-12', '2023-01', dtype='datetime64[D]')
print(all_dates_solution1)
print(all_dates_solution2)


['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06', '2022-12-07', '2022-12-08', '2022-12-09', '2022-12-10', '2022-12-11', '2022-12-12', '2022-12-13', '2022-12-14', '2022-12-15', '2022-12-16', '2022-12-17', '2022-12-18', '2022-12-19', '2022-12-20', '2022-12-21', '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25', '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29', '2022-12-30', '2022-12-31']
['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
 '2022-12-06' '2022-12-07' '2022-12-08' '2022-12-09' '2022-12-10'
 '2022-12-11' '2022-12-12' '2022-12-13' '2022-12-14' '2022-12-15'
 '2022-12-16' '2022-12-17' '2022-12-18' '2022-12-19' '2022-12-20'
 '2022-12-21' '2022-12-22' '2022-12-23' '2022-12-24' '2022-12-25'
 '2022-12-26' '2022-12-27' '2022-12-28' '2022-12-29' '2022-12-30'
 '2022-12-31']


#### Exercise: Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)

In [238]:
arr_random_1 = np.random.rand(10) * 10
print(arr_random_1.astype("int"))
print(np.int64(arr_random_1))


[5 8 1 5 6 1 7 6 4 8]
[5 8 1 5 6 1 7 6 4 8]


#### Exercise: Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [239]:
m_5x5 = np.int64(np.random.rand(5,5) * 4)
print(m_5x5)

[[3 2 2 2 1]
 [2 0 1 1 1]
 [3 1 1 1 2]
 [0 1 3 2 0]
 [2 0 0 3 1]]


#### Exercise: Consider a generator function that generates 10 integers and use it to build an array (★★☆)

In [240]:
def generate():
   for n in range(10):
       yield n
gen_arr_10int = np.fromiter(generate(),dtype=int)

print(gen_arr_10int)

[0 1 2 3 4 5 6 7 8 9]


#### Exercise: Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [241]:
print(np.linspace(0,1,10)[1:-1])

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


#### Exercise: Create a random vector of size 10 and sort it (★★☆)

In [242]:
print(np.sort(np.random.rand(10)))

[0.04669332 0.06895543 0.32890862 0.38087901 0.4125946  0.43016002
 0.51928142 0.53152395 0.608477   0.89055887]


#### Exercise: Consider two random array A and B, check if they are equal (★★☆)

In [243]:
A = np.random.rand(2,10)
B = np.random.rand(2,10)
print(np.allclose(A, B))
print(np.isclose(A, B))
##print(np.all(A, B)) # only integer scalar arrays
##print(np.any(A, B)) # only integer scalar arrays
print(np.equal(A, B))
print(A == B)


False
[[False False False False False False False False False False]
 [False False False False False False False False False False]]
[[False False False False False False False False False False]
 [False False False False False False False False False False]]
[[False False False False False False False False False False]
 [False False False False False False False False False False]]


#### Exercise: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★★)
Suggestion: check how to calculate the "square of a matrix"

In [244]:
cartesian_coordinates = np.random.rand(10,2)
print(cartesian_coordinates)
#print(np.arctan(cartesian_coordinates[:,1]/cartesian_coordinates[:,0]).reshape(-1,1))
#print(np.sqrt((cartesian_coordinates[:,1])**2 + (cartesian_coordinates[:,0])**2).reshape(-1,1))
polar_coordinates = np.array([np.sqrt((cartesian_coordinates[:,0])**2 + (cartesian_coordinates[:,1])**2), np.arctan(cartesian_coordinates[:,1]/cartesian_coordinates[:,0])])
print(polar_coordinates.reshape(10,2))


[[0.01516205 0.31255627]
 [0.80065126 0.98926403]
 [0.15856824 0.11524606]
 [0.88725719 0.02014526]
 [0.67657494 0.02092618]
 [0.46020786 0.30195386]
 [0.88746659 0.91823554]
 [0.74620722 0.92098822]
 [0.99508859 0.52115866]
 [0.26251292 0.04910423]]
[[0.31292381 1.27266876]
 [0.19602434 0.88748586]
 [0.67689849 0.55042475]
 [1.27700958 1.18534574]
 [1.12330212 0.26706602]
 [1.52232451 0.89038597]
 [0.62848149 0.0227012 ]
 [0.03091973 0.58066894]
 [0.80243639 0.88985195]
 [0.48245161 0.18491758]]


#### Exercise: Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [245]:
rand_vect = np.random.randint(1,20,size=10)
print(rand_vect)
print(rand_vect.max())
rand_vect[rand_vect == rand_vect.max()]=0
print(rand_vect)

[16  7 14  6 17 16  5 12  4  8]
17
[16  7 14  6  0 16  5 12  4  8]


#### Exercise: How to print all the values of an array? (★★☆)

In [246]:
rand_vect = np.random.rand(12,20)*20 + 3

with np.printoptions(threshold=np.inf):
    print(rand_vect)
print(rand_vect.tolist())

[[22.53238441 12.47649922 12.30773114 13.45638463 14.77795756 14.10681509
   5.49719506  7.98676403 20.34716799 20.68880122  5.45190405  7.18790538
  11.4582314  12.75381984 13.60107516 11.31488097 17.03371395  9.79696128
   3.62498586 14.97702986]
 [13.24373065 19.79953926  6.22053231  8.06213541 20.77762618  8.34448778
   6.58530476  3.12130499 18.47722426 20.72379454 11.13677981 14.43104103
  10.68904412 11.86370907 10.38763181  6.92105086  9.73571255 16.88566505
   9.39356605 16.66437849]
 [ 9.72352191 17.40095165 17.37662394 18.24961131  9.31836802 10.23531338
   8.9702775   7.79696777  6.16579312  9.35466177 11.80686987 10.75221362
  11.77158394 20.84608632 17.30059895 12.04187759 17.82505383 14.96821219
  12.28610692 12.27201054]
 [10.97526243  5.35529446 17.70276392 15.59305871 21.29770019 10.88582615
   7.65089735  6.47967766  5.23571431  7.03733976 13.82344888  8.39999591
   5.5665459  22.38732292 11.2894731   8.64914714 11.12436906 15.98576884
  17.87927927 11.2841935 ]
 [ 7

#### Exercise: How to convert a float (32 bits) array into an integer (32 bits) in place?
Check https://stackoverflow.com/a/4396247/5989906

In [247]:
rand_vect = np.random.rand(12,20).astype(np.float32) *20 + 3
y = rand_vect.view('int32')
y[:] = rand_vect
print(y)

[[18 21  7  4 11 14  7 21 20  5 15 21 19  3 18 22 12  5 15  5]
 [22 13 16 10  8 11 16  9  3 10 22 13 12 17  9 15  7 19 21  9]
 [17  8  4 10 10  6 10  9 10  3  5 14  4  6  3 11 19 13 18  8]
 [10 19 19 10 10  6 16  8 11 13 17 14 14  5 15  4 16 15  9 18]
 [19 10  9  9 15 11 18 10 12  8  5  9 21 22  5  6  8  5 10 11]
 [ 8 15 16 18 22 21 15 20 11 22 17  3 22 18  4 16  4 11 21 21]
 [12 19 20 20 15 12 13 11  4  4 22 21 10 14 18 21  6 16 10  7]
 [15  8 20  9 14  3 17  8  7 20  3 18 10  6  5 18 19 22 21 19]
 [13 19  9 14  8  7 19 16 11 20 19 10  6 19  5 20  9  4 15  8]
 [21  4 20  8  9 11 16  3  8 15 21 16 11  6 15 19  5  8 10  3]
 [19 11 22  9  8 14 12 18  7 16 15  4 15 12 19 12 19  7 13 16]
 [ 5 11 14 15  3  6 16 22 11 15  4 16 14 21  5 11  6 22 14 19]]


#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [248]:
mtx_a = np.random.randint(1,20,size=(3,3))
print(mtx_a)
print(mtx_a.mean(axis=1))
print(mtx_a - mtx_a.mean(axis=1).reshape(-1,1))
print(mtx_a - mtx_a.mean(axis=1, keepdims=True))

[[18  5 10]
 [10  4  1]
 [18  1  5]]
[11.  5.  8.]
[[ 7. -6. -1.]
 [ 5. -1. -4.]
 [10. -7. -3.]]
[[ 7. -6. -1.]
 [ 5. -1. -4.]
 [10. -7. -3.]]


#### Exercise: How to sort an array by the nth column? (★★☆)

In [249]:
mtx_a = np.random.randint(1,20,size=(3,5))
print(mtx_a)
print()
#mtx_a = mtx_a.tolist()
cols = [1]
print(mtx_a[np.lexsort(mtx_a.T[cols])])
print()
print(mtx_a[ mtx_a[:,1].argsort()])
print(mtx_a[ mtx_a[:,1].argsort(),:])
mtx_a.view('i8,i8,i8,i8,i8').sort(order=['f1'], axis=0)
print(mtx_a)


[[ 6 17 15 10 17]
 [15 16  3 13 19]
 [ 6  1  1  8 10]]

[[ 6  1  1  8 10]
 [15 16  3 13 19]
 [ 6 17 15 10 17]]

[[ 6  1  1  8 10]
 [15 16  3 13 19]
 [ 6 17 15 10 17]]
[[ 6  1  1  8 10]
 [15 16  3 13 19]
 [ 6 17 15 10 17]]
[[ 6  1  1  8 10]
 [15 16  3 13 19]
 [ 6 17 15 10 17]]


#### Exercise: Find the position of a the minimum of a 2D matrix? (★★☆)

In [250]:
mtx_a = np.random.randint(1,20,size=(3,5))
print(mtx_a.min())
print(mtx_a == mtx_a.min())
print(np.where(mtx_a == mtx_a.min()))

2
[[False False False False False]
 [ True False False False False]
 [False False False False False]]
(array([1]), array([0]))


#### Exercise: Read an image using openCV, check its dimensions, normalize the numbers and show the image (★★★)
Check: https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

In [251]:
from cv2 import *
path = "/workspace/ml_pre_work/02-numpy/assets/1D.png"
img = cv2.imread(path)
print(img.size)
print(img.shape)
#img = (img - img.mean()) / img.std()
norm_img = np.zeros((img.shape[0],img.shape[1]))
final_img = cv2.normalize(img,  norm_img, 0, 255, cv2.NORM_MINMAX)
#cv2.imshow('image', img)
cv2.imwrite('/workspace/ml_pre_work/02-numpy/assets/normalized_image.jpg', final_img)

825300
(393, 700, 3)


True

#### Exercise: Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [252]:
A = np.random.randint(0,10,(3,2,3,4))
print(A.shape)
#print(A)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)
sum = A.sum(axis=(-2,-1))
print(sum)

(3, 2, 3, 4)
[[61 52]
 [63 44]
 [60 59]]
[[61 52]
 [63 44]
 [60 59]]


#### Exercise: How to get the diagonal of a dot product? (★★★)

In [253]:
A = np.random.randint(0,10,(3,2))
B = np.random.randint(0,10,(2,3))
c = np.dot(A,B)
print(c)
print(c.diagonal())

[[34 28 20]
 [23 56 40]
 [53 56 40]]
[34 56 40]


#### Exercise: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [254]:
A = np.random.randint(0,10,(5,5,3))
B = np.random.randint(0,10,(5,5))
C = (A.T * B.T).T
print(C)
D = A * B[:,:,None]
print(D)
print(D == C)

[[[36 48  6]
  [81 18 36]
  [ 0  0  0]
  [56 16 32]
  [18 18 24]]

 [[24 30  6]
  [45 25 40]
  [36 12  0]
  [ 0  0  0]
  [18 30 30]]

 [[ 9  9  8]
  [ 0  0 15]
  [40 10 15]
  [ 0 36 81]
  [28  8 32]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 7 63 21]
  [ 6  6  6]
  [ 0  0  0]]

 [[24 24 42]
  [ 0  0  0]
  [35  0 14]
  [ 0  0  4]
  [ 0 18  9]]]
[[[36 48  6]
  [81 18 36]
  [ 0  0  0]
  [56 16 32]
  [18 18 24]]

 [[24 30  6]
  [45 25 40]
  [36 12  0]
  [ 0  0  0]
  [18 30 30]]

 [[ 9  9  8]
  [ 0  0 15]
  [40 10 15]
  [ 0 36 81]
  [28  8 32]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 7 63 21]
  [ 6  6  6]
  [ 0  0  0]]

 [[24 24 42]
  [ 0  0  0]
  [35  0 14]
  [ 0  0  4]
  [ 0 18  9]]]
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  Tr

#### Exercise: How to swap two rows of an array? (★★★)

In [255]:
A = np.random.randint(0,10,(5,5))
print(A)
A[-2:] = np.flip(A[-2:],axis=0)
print(A)

[[9 4 7 8 5]
 [9 1 5 7 2]
 [8 2 3 8 8]
 [4 6 3 4 6]
 [5 4 3 6 7]]
[[9 4 7 8 5]
 [9 1 5 7 2]
 [8 2 3 8 8]
 [5 4 3 6 7]
 [4 6 3 4 6]]


#### Exercise: Read an image using openCV and tranpose it. What did you get exactly? Was the image rotated? Moved? Reflected with respect to an axis? (★★★)

In [256]:
path = "/workspace/ml_pre_work/02-numpy/assets/1D.png"
img = cv2.imread(path)
print(img.size)
print(img.shape)

final_img = cv2.transpose(img)
print(final_img.size)
print(final_img.shape)

cv2.imwrite('/workspace/ml_pre_work/02-numpy/assets/transposed_image.jpg', final_img)
#Reflected with respect to xx axis and rotated 90 degrees right to left

825300
(393, 700, 3)
825300
(700, 393, 3)


True

#### Exercise: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [257]:
from numpy.lib import stride_tricks

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### Exercise: How to find the most frequent value in an array? (★★★)

In [258]:
vals, counts = np.unique(R, return_counts=True)
mode_value = np.argwhere(counts == np.max(counts))
print("list of modes: ", vals[mode_value].flatten().tolist())
print("mode frequency: ", np.max(counts))

list of modes:  [4, 5, 6, 7, 8, 9, 10, 11]
mode frequency:  4


#### Exercise: How to get the n largest values of an array (★★★)

In [259]:
N = np.random.randint(0,200,(2,2,3,2))
print(N)
n = 4
ind = np.unravel_index(np.argsort(N, axis=None), N.shape) #for N-dimensional array
print(np.unique(N[ind])[-n:])

[[[[ 68  68]
   [128 199]
   [ 17 184]]

  [[103   9]
   [179  93]
   [118 147]]]


 [[[131  59]
   [131 151]
   [  9  64]]

  [[ 32 106]
   [ 43  81]
   [ 96  79]]]]
[151 179 184 199]


#### Exercise: Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [260]:
A_vect = np.linspace(1,200,2000)
pow_vect = np.linspace(3,3,2000)
A_vect_1 = A_vect**3
A_vect_2 = np.power(A_vect,3)
A_vect = np.linspace(1,200,2000)
A_vect_3 = np.float_power(A_vect, pow_vect)
#print(A_vect_3)
print(np.sum(A_vect_1 == A_vect_2))
print(np.sum(A_vect_1 == A_vect_3))
print(np.sum(A_vect_2 == A_vect_3))

2000
2000
2000


#### Exercise: Given a two dimensional array, how to extract unique rows? (★★★)

In [261]:
Z = np.random.randint(0,2,(16,4))
Z_unique = np.unique(Z, axis=0)
print(Z_unique)

[[0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 1]]


#### Exercise: Can you have arrray of strings? can you mix different data types in the same array? Can you operate (add, sub, mult) arrays with different data types? (★★★)

In [262]:
ARR = np.array([["rtef",("fag",34.3),"fag"], ["rtef",45,"fag"], ["rt","fag",23], ["ref","fag","fa"]])
print(ARR)
print(ARR.dtype)
ARR = np.array([[27.8,"fag","fag"], ["rtef",45,"fag"], ["rt","fag",23], ["ref",True,"fa"]])
print(ARR)
print(ARR.dtype)

[['rtef' ('fag', 34.3) 'fag']
 ['rtef' 45 'fag']
 ['rt' 'fag' 23]
 ['ref' 'fag' 'fa']]
object
[['27.8' 'fag' 'fag']
 ['rtef' '45' 'fag']
 ['rt' 'fag' '23']
 ['ref' 'True' 'fa']]
<U32


/tmp/ipykernel_1241/1237648183.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ARR = np.array([["rtef",("fag",34.3),"fag"], ["rtef",45,"fag"], ["rt","fag",23], ["ref","fag","fa"]])
