<img src="./assets/numpy_logo.png" alt="logo" width="400"/>

## Introduction to numpy

NumPy stands for 'Numerical Python'. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrices, along with many high-level mathematical functions that operate on these arrays and matrices. It contains among other things:

→ a powerful N-dimensional array object

→ sophisticated (broadcasting) functions

→ tools for integrating C/C++ and Fortran code

→ useful linear algebra, Fourier transform, and random number capabilities

## Installing NumPy
When you want to work with numpy locally, you should run the following commands:

You can install NumPy with:\
`pip install numpy`\
or\
`conda install numpy`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.

## Why should we use NumPy?

Numpy is a library to perform numerical calculation in python. We will use it mainly because it allows us to create and modify matrices, and to do operations on them with ease.

NumPy is, like Pandas, Matplotlib or Scikit-Learn, one of the packages that you cannot miss when you are learning Machine Learning, mainly because this library provides a matrix data structure that has some benefits over regular Python lists. Some of these benefits are: being more compact, quicker access to reading and writing articles, being more convenient and more efficient.

For example, we will see later in the bootcamp that working with images means dealing with three-dimensional matrices as large as 3840 x 2160, which means we will have 3×3840×2160 = 24883200 entries!!! 😱😱😱.

Working with matrices of that magnitude is practically impossible to carry out with lists and dictionaries if one wants to have an efficient and fast programming.

#### Exercise: Import the numpy package under the name `np` (★☆☆)

`numpy` is commonly imported as `np` so we highly recommend to put this alias.

In [4]:
import numpy as np

## What is an array and why it is importante for machine learning?

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.


![alt text](assets/1D.png "1D")

We can have arrays from several dimension. Neural networks sometimes deal with 4D arrays. An array is known as the central data structure of the NumPy library. Array in NumPy is called as NumPy Array. Later, we will use also other kind of arrays thar are called: Tensors.

![alt text](./assets/3D.png "3D")

#### Exercise: Print the numpy version and the configuration (★☆☆)

You can print the version of any package of Python using `name_of_package.__version__`

In [5]:
import numpy as np
print(np.__version__)

1.22.1


#### Exercise: Create a null vector of size 10 (★☆☆)

A `null vector` is an array of zeros (`0`), also called `inicializacion vector`.

Check de function `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise: Create a vector of ones with size 10 (★☆☆)
Check de function `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise: Create an 1D array with specific start value, end value and number of values (★☆☆)

Check the function `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [8]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Run: Create a vector (1D array) with random integers from 10 to 49 and dimension 1x35 (★☆☆)

When `dimension` is expressed `1x35` it means: One dimension array with 35 items (length=35).

Check the function `np.random` which allows you to create random arrays (https://numpy.org/doc/1.16/reference/routines.random.html)

In [9]:
import numpy as np

## 10 random numbers between (0, 1)
print(np.random.random(10))
## 35 random numbers between (10, 49)
print(np.random.random(35)*39 + 10)  

[0.41327165 0.29976058 0.86990539 0.75482848 0.40335102 0.22190692
 0.67641271 0.02639257 0.94454136 0.85229209]
[37.01431029 24.81532749 19.12775508 29.21425806 38.90637416 41.25680813
 40.30164094 36.28878039 14.86911448 14.59903179 46.79971852 34.98973228
 19.292615   28.94318659 12.31936512 34.79157023 46.83591863 26.46872762
 12.95966598 32.38517567 11.92513502 15.38383771 32.1917903  44.2176867
 36.14975316 11.13878796 30.82166574 25.74419705 48.4965762  17.54201406
 26.34582645 45.02240469 21.08505859 43.93875267 47.44711382]


In [10]:
## Two ways to create numbers with normal distribution
print(np.random.rand(10)) # 10 random values with distribution N(0,1)
print(np.random.normal(loc = 0, scale = 1, size = 10)) # 10 random values with distribution N(0,1)

[0.19493876 0.10915582 0.33899438 0.23919752 0.90752135 0.02751952
 0.82475212 0.63214787 0.27348458 0.07038175]
[ 1.34847708 -0.47795803  1.15484451  0.33553946  0.03955165 -0.56982523
  2.94528199 -0.93657249  1.60216668 -0.71347434]


In [11]:
## Did you notice the difference between both functions? 
print(np.random.normal(loc = -5, scale = 33, size = 10)) # 10 random values with distribution N(-5,33)

[-36.32647069  33.98455634  17.05569442 -23.38641967   8.46686016
  17.81142201   9.08596287 -18.22805568 -12.24445169 -27.87772875]


In [12]:
## 10 random values with uniform distribution. That is, all values have the same probability
print(np.random.uniform(-30,100,10)) # All values are between -30 and 100.

[ 78.99590358  -3.67245719  78.10036254   7.98023343  95.96931126
  19.77718918  83.4280562   85.49183161 -11.04702573  77.97438212]


In [13]:
# 10 integers values between 0 and 100.
print(np.random.randint(0, 100, 10))

[51 65 71 16 80 39  4 85 92 92]


In [14]:
# 10 random values with Chi distribution with 5 degrees of freedom
print(np.random.chisquare(5,10))

[5.82819891 5.01702294 3.13550186 5.852718   3.36167573 2.68683886
 5.67069793 3.16907167 2.84992403 4.85968263]


The above examples are the most common distribution and random values you will learn throughout the bootcamp. Now, let's deal with those arrays.

#### Exercise: Reverse one of the last vector we created before (first element becomes last) (★☆☆)
Try with `[::-1]`

In [15]:
rand_int_vect = np.random.randint(0, 100, 10)
print(rand_int_vect)
print(rand_int_vect[::-1])

[86 54 47 74 18 67 38 35 91  3]
[ 3 91 35 38 67 18 74 47 54 86]


#### Exercise: Create a 5x5 identidy matrix (★☆☆)
Check the function `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [16]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Exercise: Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
Check the function `where`(https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [17]:
print(np.where(np.array([1,2,0,0,4,0]) != 0)[0])

[0 1 4]


#### Exercise: Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Check the function `min`(https://numpy.org/devdocs/reference/generated/numpy.where.html) and `max`(https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [18]:
arr_10_by_10 = np.random.random((10,10))
print(arr_10_by_10.min())
print(arr_10_by_10.max())

0.00837695776382319
0.9831164577527541


#### Exercise: Create a random vector of size 30 and find the mean value (★☆☆)

In [19]:
print(np.random.random(30).mean())

0.46373998238219366


#### Exercise: Define a function with input your date of birth (yyyy/mm/dd) that returns a random array with the following dimensions: (★★☆)
$$yyyy-1900 \times |mm - dd|$$

In [20]:
def birth_date(date_of_birth: str) -> np.array:
    date = date_of_birth.split("/")
    size = (int(date[0]) - 1900, np.abs(int(date[1]) - int(date[2])))
    return np.random.random(size) 

birthdate = input("enter your birthday: ")
print(birth_date(birthdate).shape)

(90, 2)


## What is the difference between Python List and a Numpy Array?

- Python list can contain elements with different data types whereas Numpy Array‘s elements are always homogeneous (same data types).
- NumPy arrays are faster and more compact than Python lists.

## Why NumPy Arrays are faster than Lists?

- NumPy Array uses fixed memory to store data and less memory than Python lists.
- Contiguous memory allocation in NumPy Arrays.

#### Exercise: Convert the list `my_list = [1, 2, 3]` to numpy array (★☆☆)

In [21]:
my_list = [1, 2, 3]
numpy_my_list = np.array(my_list)
print(my_list)
print(numpy_my_list)

[1, 2, 3]
[1 2 3]


#### Exercise: Convert the tuple `my_list = (1, 2, 3)` to numpy array (★☆☆)

In [22]:
my_list = (1, 2, 3)
numpy_my_list = np.array(my_list)
print(my_list)
print(numpy_my_list)

(1, 2, 3)
[1 2 3]


#### Exercise: Convert the list of tuples `my_list = [(1,2,3), (4,5)]` to numpy array (★☆☆)

In [23]:
my_list = [(1, 2, 3), (4,5)]
numpy_my_list = np.array(my_list, dtype=np.ndarray)
print(my_list)
print(numpy_my_list)

[(1, 2, 3), (4, 5)]
[(1, 2, 3) (4, 5)]


#### Exercise: Resize a random array of dimensions 5x12 into 12x5 (★☆☆)
Check `reshape`from `numpy`(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [24]:
size1 = 5,12
size2 = 12,5
arr1 = np.random.random(size1)
arr2 = arr1.reshape(size2)
print(arr1.shape)
print(arr2.shape)

(5, 12)
(12, 5)


#### Exercise: Create a function that normalize a 5x5 random matrix (★☆☆)
Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :
$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$


In [25]:
arr_to_normalize = np.random.random((5,5))
arr_normalized = (arr_to_normalize - arr_to_normalize.mean()) / arr_to_normalize.std()
print(arr_normalized)

[[ 1.37902245  0.63366442 -1.85392141 -0.67280942 -1.27971121]
 [-0.41060805  0.26560947 -0.62306046 -0.85757352  0.54286787]
 [-1.25048505  0.15514357 -0.71510664  0.32499906  1.3108813 ]
 [ 0.91076416  0.48413218 -0.1870968   1.37306665 -1.80356001]
 [ 0.04576267 -1.17924819  1.11707151  1.35561717  0.93457828]]


## Stacking numpy arrays

Stacking is used to join a sequence of same dimension arrays along a new axis.
`numpy.stack(arrays,axis)` : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

### You have two ways to do it:


![alt text](./assets/stack.jpeg "stack")


### or


![alt text](./assets/stack2.jpeg "stack")




#### Exercise: Generate two random arrays with integers and apply the stacking using `stack` (★★☆)

In [26]:
arr_1 = np.random.randint(0, 10, (2,2))
arr_2 = np.random.randint(0, 10, (2,2))
print(arr_1)
print()
print(arr_2)
print()
print(np.stack((arr_1, arr_2)))

[[3 5]
 [3 1]]

[[9 7]
 [7 2]]

[[[3 5]
  [3 1]]

 [[9 7]
  [7 2]]]


#### Exercise: Generate two random arrays with integers and apply the stacking using `hstack` and `vstack` (★★☆)

In [27]:
arr_1 = np.random.randint(0, 10, (2,2))
arr_2 = np.random.randint(0, 10, (2,2))
print(arr_1)
print()
print(arr_2)
print()
print(np.hstack((arr_1, arr_2)))
print()
print(np.vstack((arr_1, arr_2)))

[[2 2]
 [1 3]]

[[5 3]
 [4 5]]

[[2 2 5 3]
 [1 3 4 5]]

[[2 2]
 [1 3]
 [5 3]
 [4 5]]


## Basic maths in numpy

You can make typical math operations like:

- Addition,Subtraction,Multiplication and Division between two arrays using numpy.
- Operation on array using sum() & cumsum() function.
- Minimum and Maximum value from an array
- Exponent/Power , Square Root and Cube Root functions

or even apply common trigonometric functions:

- `numpy.sin()`:  Sine (x) Function
- `numpy.cos()`: Cosine(x) Function
- `numpy.tan()`: Tangent(x)Function
- `numpy.sinh()`: Hyperbolic Sine (x) Function
- `numpy.cosh()`: Hyperbolic Cosine(x) Functionv
- `numpy.tanh()`: Hyperbolic Tangent(x)Function
- `numpy.arcsin()`: Inverse Sine Function
- `numpy.arccos()`: Inverse Cosine Function
- `numpy.arctan()`: Inverse Tangent Function
- `numpy.pi`: pi value
- `numpy.hypot(w,h)`: For calculating Hypotenuse $c = \sqrt{(w^2 + h^2)}$
- `numpy.rad2deg()`: Radians to degrees
- `numpy.deg2rad()`: Degrees to radians

#### Exercise: Generate two random 8 - dimensional vectors and apply the most common operation between vectors:  addition, substraction, multiplication, division(★☆☆)

Check the math functions here: https://numpy.org/doc/stable/reference/routines.math.html

In [28]:
vect_1 = np.random.random(8)
vect_2 = np.random.random(8)

print(vect_1 + vect_2)
print(vect_1 - vect_2)
print(vect_1 * vect_2)
print(vect_1 / vect_2)

[0.93306603 0.92126902 0.9810943  0.89412519 1.20867094 0.43266807
 1.248893   1.05081478]
[ 0.75911875  0.3800815  -0.04958063 -0.45784147 -0.10544559  0.08762106
 -0.48859214  0.45888135]
[0.07358773 0.17606866 0.24002194 0.14746026 0.36244167 0.04488105
 0.33025286 0.2234099 ]
[9.72814761 2.40462037 0.90378997 0.32270302 0.83951866 1.50787896
 0.43758697 2.55044917]


#### Exercise: Generate two random matrices with dimensions between 5 and 10, e.g. 5x7 vs 8x9 and try. Were you able to do the matrix multiplication? why? (★★☆) 

In [29]:
matrix_1 = np.random.random((np.random.randint(5,10), np.random.randint(5,10)))
matrix_2 = np.random.random((np.random.randint(5,10), np.random.randint(5,10)))


#print(matrix_1 * matrix_2) #ValueError: operands could not be broadcast together with shapes (9,7) (6,5) 

#### Exercise: Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array) Were you able to do the matrix multiplication? (★★☆) 

$$ a = \left(\begin{matrix}
0 & 1 & 2\\ 
3 & 4 & 5\\ 
6 & 7 & 8
\end{matrix}\right)$$

$$ b = \left(\begin{matrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{matrix}\right)$$




In [30]:
a = np.linspace(0, 8, 9).reshape((3,3))
b = np.linspace(2, 10, 9).reshape((3,3))
print(a)
print(b)
print(a * b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 0.  3.  8.]
 [15. 24. 35.]
 [48. 63. 80.]]


#### Exercise: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★★☆)

In [31]:
matrix_1 = np.random.random((5, 3))
matrix_2 = np.random.random((3, 2))

print(np.dot(matrix_1, matrix_2))

[[1.1793376  0.69425   ]
 [1.37313616 0.87325826]
 [1.40066114 0.90542032]
 [1.22961841 0.82190461]
 [1.11642055 0.73320994]]


## Data types

Do you think the following preposition is true?
`8==8`

Surely you will definetely say yes, which is true mathematically, but computationally it is not always the same, at least in terms of memory. For example, run the following cell:

In [32]:
import sys

# int64
x = np.array(123)
print("int64: " + str(sys.getsizeof(x)))

# int8
x = np.array(123,dtype=np.int8)
print("int8: " + str(sys.getsizeof(x)))

# float32
x = np.array(123,dtype=np.float32)
print("float32: " + str(sys.getsizeof(x)))

int64: 104
int8: 97
float32: 100


## It turns out that there are many computational representation of the same number and you can create arrays with different Data Types (dtypes) depending what you need:

- Boolean : `np.bool_`
- Char : `np.byte`
- Short : `np.short`
- Integer : `np.short`
- Long : `np.int_`
- Float : `np.single`&np.float32`
- Double :`np.double`&`np.float64`
- `np.int8`: integer (-128 to 127)
- `np.int16`:integer( -32768 to 32767)
- `np.int32`: integer(-2147483648 to 2147483647)
- `np.int64`:integer( -9223372036854775808 to 9223372036854775807)


Sometimes, you will need to load, create or export arrays from different data types.


## Harder exercises

The next exercises are related with real situations you could face while you are working in data science and machine learning and we will be frequently talking about matrices and bidimensional arrays.

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [33]:
print("Original matrix:\n")
X = np.random.rand(3, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
print("\nSubtract the mean of each column of the said matrix:\n")
Z = X - X.mean(axis=0, keepdims=True)
print(Z)

Original matrix:

[[0.8374258  0.17539485 0.92684226 0.70326775 0.61424249 0.53103776
  0.07041893 0.28559734 0.18780209 0.05054095]
 [0.6534131  0.8904016  0.68913148 0.56059017 0.36056718 0.31643374
  0.05556657 0.64331049 0.88995799 0.30952254]
 [0.08350962 0.5419252  0.73651813 0.68074849 0.98027456 0.03253335
  0.91818658 0.34728665 0.88467325 0.23604361]]

Subtract the mean of each row of the said matrix:

[[ 0.39916878 -0.26286217  0.48858524  0.26501073  0.17598547  0.09278073
  -0.36783809 -0.15265968 -0.25045494 -0.38771607]
 [ 0.11652362  0.35351212  0.15224199  0.02370068 -0.17632231 -0.22045574
  -0.48132292  0.106421    0.3530685  -0.22736695]
 [-0.46066032 -0.00224474  0.19234819  0.13657855  0.43610461 -0.5116366
   0.37401663 -0.1968833   0.34050331 -0.30812633]]

Subtract the mean of each column of the said matrix:

[[ 0.31264296 -0.36051237  0.14267831  0.05506562 -0.03745225  0.23770281
  -0.27763843 -0.13980082 -0.46634236 -0.14816142]
 [ 0.12863026  0.35449438 -0.

#### Exercise: How to get the dates of yesterday, today and tomorrow? (★★☆)
Check `np.datetime64`, `np.timedelta64` in numpy (https://numpy.org/doc/stable/reference/arrays.datetime.html)

In [34]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("today", today)
print("yesterday", yesterday)
print("tomorrow", tomorrow)

today 2022-01-20
yesterday 2022-01-19
tomorrow 2022-01-21


#### Exercise: How to get all the dates corresponding to the month of December 2022? (★★☆)
Combine `arange`with `datetime`


In [35]:
all_dates_solution1 = [(np.datetime64('2022-12', 'D') + np.timedelta64(day, 'D')).astype("str") for day in np.arange(31)]
all_dates_solution2 = np.arange('2022-12', '2023-01', dtype='datetime64[D]')
print(all_dates_solution1)
print(all_dates_solution2)


['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06', '2022-12-07', '2022-12-08', '2022-12-09', '2022-12-10', '2022-12-11', '2022-12-12', '2022-12-13', '2022-12-14', '2022-12-15', '2022-12-16', '2022-12-17', '2022-12-18', '2022-12-19', '2022-12-20', '2022-12-21', '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25', '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29', '2022-12-30', '2022-12-31']
['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
 '2022-12-06' '2022-12-07' '2022-12-08' '2022-12-09' '2022-12-10'
 '2022-12-11' '2022-12-12' '2022-12-13' '2022-12-14' '2022-12-15'
 '2022-12-16' '2022-12-17' '2022-12-18' '2022-12-19' '2022-12-20'
 '2022-12-21' '2022-12-22' '2022-12-23' '2022-12-24' '2022-12-25'
 '2022-12-26' '2022-12-27' '2022-12-28' '2022-12-29' '2022-12-30'
 '2022-12-31']


#### Exercise: Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)

In [36]:
arr_random_1 = np.random.rand(10) * 10
print(arr_random_1.astype("int"))
print(np.int64(arr_random_1))


[0 2 0 6 5 2 9 9 0 0]
[0 2 0 6 5 2 9 9 0 0]


#### Exercise: Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
m_5x5 = np.int64(np.random.rand(5,5) * 4)
print(m_5x5)

[[3 0 2 1 3]
 [1 2 0 1 3]
 [2 1 0 0 1]
 [1 2 2 2 2]
 [3 1 2 0 0]]


#### Exercise: Consider a generator function that generates 10 integers and use it to build an array (★★☆)

In [38]:
def generate():
   for n in range(10):
       yield n
gen_arr_10int = np.fromiter(generate(),dtype=int)

print(gen_arr_10int)

[0 1 2 3 4 5 6 7 8 9]


#### Exercise: Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
print(np.linspace(0,1,10)[1:-1])

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


#### Exercise: Create a random vector of size 10 and sort it (★★☆)

In [40]:
print(np.sort(np.random.rand(10)))

[0.00297293 0.0340971  0.11066039 0.20932344 0.22153747 0.47572389
 0.58637132 0.68476034 0.71902952 0.82015418]


#### Exercise: Consider two random array A and B, check if they are equal (★★☆)

In [41]:
A = np.random.rand(2,10)
B = np.random.rand(2,10)
print(np.allclose(A, B))
print(np.isclose(A, B))
##print(np.all(A, B)) # only integer scalar arrays
##print(np.any(A, B)) # only integer scalar arrays
print(np.equal(A, B))
print(A == B)


False
[[False False False False False False False False False False]
 [False False False False False False False False False False]]
[[False False False False False False False False False False]
 [False False False False False False False False False False]]
[[False False False False False False False False False False]
 [False False False False False False False False False False]]


#### Exercise: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★★)
Suggestion: check how to calculate the "square of a matrix"

In [42]:
cartesian_coordinates = np.random.rand(10,2)
print(cartesian_coordinates)
#print(np.arctan(cartesian_coordinates[:,1]/cartesian_coordinates[:,0]).reshape(-1,1))
#print(np.sqrt((cartesian_coordinates[:,1])**2 + (cartesian_coordinates[:,0])**2).reshape(-1,1))
polar_coordinates = np.array([np.sqrt((cartesian_coordinates[:,0])**2 + (cartesian_coordinates[:,1])**2), np.arctan(cartesian_coordinates[:,1]/cartesian_coordinates[:,0])])
print(polar_coordinates.reshape(10,2))


[[0.70806898 0.57090846]
 [0.26807204 0.19744843]
 [0.22458074 0.6843351 ]
 [0.25136786 0.85176649]
 [0.05256817 0.69607349]
 [0.1388255  0.35440341]
 [0.96049065 0.39276713]
 [0.93462915 0.14071305]
 [0.70766954 0.42621054]
 [0.29803832 0.63800965]]
[[0.90955932 0.33293919]
 [0.72024373 0.8880833 ]
 [0.69805567 0.38062356]
 [1.03769375 0.94516232]
 [0.82610629 0.70418971]
 [0.67856414 0.63483732]
 [1.25369667 1.28382849]
 [1.4954184  1.19745163]
 [0.38817524 0.14943265]
 [0.54208944 1.13378249]]


#### Exercise: Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [43]:
rand_vect = np.random.randint(1,20,size=10)
print(rand_vect)
print(rand_vect.max())
rand_vect[rand_vect == rand_vect.max()]=0
print(rand_vect)

[ 6 15  1  5 18 18 13  7  6  8]
18
[ 6 15  1  5  0  0 13  7  6  8]


#### Exercise: How to print all the values of an array? (★★☆)

In [44]:
rand_vect = np.random.rand(12,20)*20 + 3

with np.printoptions(threshold=np.inf):
    print(rand_vect)
print(rand_vect.tolist())

[[13.53939132 10.02764836  9.53453747  4.29825661  7.16409758 10.13942022
  12.19281883 18.22155479 16.00296833  4.07019306 18.3303582  15.32031459
   3.42626154 15.89334785 10.39994109  7.98275493 10.07859526 15.97117215
  19.97082714  5.79747013]
 [13.69161789  4.94019755  6.82684736 17.5028286  14.98828921  4.70879158
   6.99763136 12.99809904  8.70724337 10.28118663 19.14918195  4.85955399
   3.8623723   8.19579268 14.93784944  8.77786724 12.58897279  9.11487943
  17.26073551 13.65271847]
 [17.2078683  17.91163699  5.39956303 22.02922708 19.41344785 10.80612341
  10.47686818 22.03173412 21.17984951  6.42702545  7.24858773  3.81569356
   7.52747051  6.89630619 12.39271005 14.32031866 14.71920465 18.67541916
  12.92850811  3.19750479]
 [11.23694539  6.09511123 12.93836677 12.76377049 12.32102741  5.10584876
   5.6322923  15.67236557 14.81538539 12.09552816 22.87536432  6.53551708
   8.0815081  15.81359506 22.95222945  3.36670571 10.38346071 17.85844429
  10.25139295 18.84128842]
 [ 5

#### Exercise: How to convert a float (32 bits) array into an integer (32 bits) in place?
Check https://stackoverflow.com/a/4396247/5989906

In [45]:
rand_vect = np.random.rand(12,20).astype(np.float32) *20 + 3
y = rand_vect.view('int32')
y[:] = rand_vect
print(y)

[[ 6 20 20 18 16 18 20 11 13 19 13 16  4  5 12 17  8 22  8 14]
 [19  8  8  4 21 22 17 13 14  5  6 15  9  7 18  9  7  8  7 15]
 [19 18 14 19 16 21  5 18 14 13 10  9  7 12 19  3 13  8  4 13]
 [11 21 17 13 10 20 11 13 12  3 19 17 10  8 16  7  5  4  8 10]
 [ 3 21 13  8 12 16 17  6  6  6 21 13  3 20 22 11 15 10 12 11]
 [20 19  4 11 11 20 19  8 11  7 13 15 19 10  5 11  6  7 14 18]
 [13 17  3 12  4 21  3 18 15 17  7 16 11 16 19  3 14  9 11  4]
 [21 22  9 19 19  3  4 12  8 21  8 13 19  5  8  7  4  4 15 15]
 [22 10  3 18 16  3 19  6 12 16  7 14  7 17  7  3 15  9 12 18]
 [17 17 15 16 21 21 12 11  5  4 20 14 16  7  8  9  3 10  9 15]
 [19  7  4  6 17 12  7  9 22  4  8 14  8 12 11  5 18 11  4  7]
 [13 13 16  7 19 10 20 18 14 12  7 18 13  6 10  9 13 21 12 11]]


#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [46]:
mtx_a = np.random.randint(1,20,size=(3,3))
print(mtx_a)
print(mtx_a.mean(axis=1))
print(mtx_a - mtx_a.mean(axis=1).reshape(-1,1))
print(mtx_a - mtx_a.mean(axis=1, keepdims=True))

[[16  8 16]
 [18 19 14]
 [ 4 13 11]]
[13.33333333 17.          9.33333333]
[[ 2.66666667 -5.33333333  2.66666667]
 [ 1.          2.         -3.        ]
 [-5.33333333  3.66666667  1.66666667]]
[[ 2.66666667 -5.33333333  2.66666667]
 [ 1.          2.         -3.        ]
 [-5.33333333  3.66666667  1.66666667]]


#### Exercise: How to sort an array by the nth column? (★★☆)

In [47]:
mtx_a = np.random.randint(1,20,size=(3,5))
print(mtx_a)
print()
#mtx_a = mtx_a.tolist()
cols = [1]
print(mtx_a[np.lexsort(mtx_a.T[cols])])
print()
print(mtx_a[ mtx_a[:,1].argsort()])
print(mtx_a[ mtx_a[:,1].argsort(),:])
mtx_a.view('i8,i8,i8,i8,i8').sort(order=['f1'], axis=0)
print(mtx_a)


[[ 5 13 15 13 13]
 [ 9 19 10 14 11]
 [12  1  2  4  2]]

[[12  1  2  4  2]
 [ 5 13 15 13 13]
 [ 9 19 10 14 11]]

[[12  1  2  4  2]
 [ 5 13 15 13 13]
 [ 9 19 10 14 11]]
[[12  1  2  4  2]
 [ 5 13 15 13 13]
 [ 9 19 10 14 11]]
[[12  1  2  4  2]
 [ 5 13 15 13 13]
 [ 9 19 10 14 11]]


#### Exercise: Find the position of a the minimum of a 2D matrix? (★★☆)

In [48]:
mtx_a = np.random.randint(1,20,size=(3,5))
print(mtx_a.min())
print(mtx_a == mtx_a.min())
print(np.where(mtx_a == mtx_a.min()))

1
[[False False False False  True]
 [False False False False False]
 [False False False False False]]
(array([0]), array([4]))


#### Exercise: Read an image using openCV, check its dimensions, normalize the numbers and show the image (★★★)
Check: https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

In [107]:
from cv2 import *
path = "/workspace/ml_pre_work/02-numpy/assets/1D.png"
img = cv2.imread(path)
print(img.size)
print(img.shape)
#img = (img - img.mean()) / img.std()
norm_img = np.zeros((img.shape[0],img.shape[1]))
final_img = cv2.normalize(img,  norm_img, 0, 255, cv2.NORM_MINMAX)
#cv2.imshow('image', img)
cv2.imwrite('/workspace/ml_pre_work/02-numpy/assets/normalized_image.jpg', final_img)

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

#### Exercise: Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,2,3,4))
print(A.shape)
#print(A)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)
sum = A.sum(axis=(-2,-1))
print(sum)

(3, 2, 3, 4)
[[51 46]
 [53 49]
 [80 39]]
[[51 46]
 [53 49]
 [80 39]]


#### Exercise: How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,2))
B = np.random.randint(0,10,(2,3))
c = np.dot(A,B)
print(c)
print(c.diagonal())

[[75 22 68]
 [87 30 80]
 [51 14 46]]
[75 30 46]


#### Exercise: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.random.randint(0,10,(5,5,3))
B = np.random.randint(0,10,(5,5))
C = (A.T * B.T).T
print(C)
D = A * B[:,:,None]
print(D)
print(D == C)

[[[21 63 56]
  [40 24 56]
  [16  4 20]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 9  6  1]
  [ 0  0  0]
  [24 24  3]
  [28 20  0]
  [ 0  0  0]]

 [[18 18 18]
  [24 24 72]
  [ 6  3  2]
  [ 0  0  0]
  [15 18  0]]

 [[ 2 18 18]
  [54 63 54]
  [ 0 56 56]
  [ 0 24 12]
  [ 6  4 14]]

 [[54 42 24]
  [ 0  0  0]
  [24 72 40]
  [21 56 14]
  [ 0  0 24]]]
[[[21 63 56]
  [40 24 56]
  [16  4 20]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 9  6  1]
  [ 0  0  0]
  [24 24  3]
  [28 20  0]
  [ 0  0  0]]

 [[18 18 18]
  [24 24 72]
  [ 6  3  2]
  [ 0  0  0]
  [15 18  0]]

 [[ 2 18 18]
  [54 63 54]
  [ 0 56 56]
  [ 0 24 12]
  [ 6  4 14]]

 [[54 42 24]
  [ 0  0  0]
  [24 72 40]
  [21 56 14]
  [ 0  0 24]]]
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  Tr

#### Exercise: How to swap two rows of an array? (★★★)

In [ ]:
A = np.random.randint(0,10,(5,5))
print(A)
A[-2:] = np.flip(A[-2:],axis=0)
print(A)

[[1 2 7 2 7]
 [8 1 8 4 6]
 [5 3 1 9 5]
 [6 3 9 5 0]
 [0 6 3 5 3]]
[[1 2 7 2 7]
 [8 1 8 4 6]
 [5 3 1 9 5]
 [0 6 3 5 3]
 [6 3 9 5 0]]


#### Exercise: Read an image using openCV and tranpose it. What did you get exactly? Was the image rotated? Moved? Reflected with respect to an axis? (★★★)

In [ ]:
path = "/workspace/ml_pre_work/02-numpy/assets/1D.png"
img = cv2.imread(path)
print(img.size)
print(img.shape)

final_img = cv2.transpose(img)
print(final_img.size)
print(final_img.shape)

cv2.imwrite('/workspace/ml_pre_work/02-numpy/assets/transposed_image.jpg', final_img)
#Reflected with respect to xx axis and rotated 90 degrees right to left

825300
(393, 700, 3)
825300
(700, 393, 3)


True

#### Exercise: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [50]:
from numpy.lib import stride_tricks

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### Exercise: How to find the most frequent value in an array? (★★★)

In [54]:
vals, counts = np.unique(R, return_counts=True)
mode_value = np.argwhere(counts == np.max(counts))
print("list of modes: ", vals[mode_value].flatten().tolist())
print("mode frequency: ", np.max(counts))

list of modes:  [4, 5, 6, 7, 8, 9, 10, 11]
mode frequency:  4


#### Exercise: How to get the n largest values of an array (★★★)

In [105]:
N = np.random.randint(0,200,(2,2,3,2))
print(N)
n = 4
ind = np.unravel_index(np.argsort(N, axis=None), N.shape) #for N-dimensional array
print(np.unique(N[ind])[-n:])

[[[[103  86]
   [157 183]
   [150  19]]

  [[ 56  44]
   [ 49  42]
   [ 85 181]]]


 [[[ 77 195]
   [ 51 170]
   [154  43]]

  [[113 161]
   [ 30 140]
   [141   0]]]]
[170 181 183 195]


#### Exercise: Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### Exercise: Given a two dimensional array, how to extract unique rows? (★★★)

#### Exercise: Can you have arrray of strings? can you mix different data types in the same array? Can you operate (add, sub, mult) arrays with different data types? (★★★)